// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://be-teal-tau.vercel.app/api/v1' | (string & {});
};

export type ErrorResponse = {
    statusCode?: number;
    message?: string;
    error?: string;
};

export type User = {
    id?: string;
    name?: string;
    email?: string;
    role?: 'learner' | 'admin';
    level?: number;
    xp?: number;
    cohortId?: string | null;
};

export type UserSummary = {
    id?: string;
    name?: string;
    role?: string;
    level?: number;
    xp?: number;
    /**
     * Tỷ lệ hoàn thành toàn bộ lộ trình (%)
     */
    completion?: number;
    /**
     * Mã màu HSL Hue đại diện đại diện
     */
    avatarHue?: number;
};

export type UserDetail = {
    id?: string;
    name?: string;
    email?: string;
    role?: string;
    title?: string;
    avatarHue?: number;
    level?: number;
    xp?: number;
    streakDays?: number;
    cohortId?: string;
    joinedAt?: string;
};

export type UserDashboardStats = {
    level?: number;
    xp?: number;
    xpThisWeek?: number;
    streakDays?: number;
    overallCompletion?: number;
    tracks?: {
        completed?: number;
        total?: number;
    };
    exercises?: {
        approved?: number;
        total?: number;
        awaitingReview?: number;
    };
    savedDocs?: {
        total?: number;
        unread?: number;
    };
};

export type CohortSummary = {
    id?: string;
    name?: string;
    learnerCount?: number;
    avgCompletion?: number;
};

export type CohortDetail = {
    id?: string;
    name?: string;
    learnerCount?: number;
    avgCompletion?: number;
    /**
     * Số ngày hoàn thành trung bình thực tế
     */
    avgRampDays?: number;
    /**
     * Số ngày mục tiêu đặt ra
     */
    targetRampDays?: number;
    createdAt?: string;
};

export type CohortDashboardStats = {
    activeLearners?: number;
    newThisWeek?: number;
    avgCompletion?: number;
    /**
     * Mức tăng trưởng % hoàn thành so với tuần trước
     */
    avgCompletionDelta?: number;
    /**
     * Số bài tập đang chờ chấm trong hàng đợi
     */
    pendingReview?: number;
    /**
     * Thời gian chờ của bài nộp cũ nhất
     */
    oldestPendingAgo?: string;
    avgRampDays?: number;
    targetRampDays?: number;
};

export type TrackSummary = {
    id?: string;
    title?: string;
    estimatedTime?: string;
    order?: number;
    lessonCount?: number;
    icon?: string;
    status?: 'completed' | 'in_progress' | 'locked';
    lessonsCompleted?: number;
    description?: string;
};

export type TrackDetail = {
    id?: string;
    title?: string;
    estimatedTime?: string;
    order?: number;
    icon?: string;
    status?: 'completed' | 'in_progress' | 'locked';
    lessonsCompleted?: number;
    description?: string;
    lessons?: Array<LessonProgressItem>;
    prevTrack?: {
        id?: string;
        title?: string;
    } | null;
    nextTrack?: {
        id?: string;
        title?: string;
    } | null;
};

export type LessonSummary = {
    id?: string;
    title?: string;
    order?: number;
    estimatedTime?: string;
};

export type LessonDetail = {
    id?: string;
    trackId?: string;
    title?: string;
    order?: number;
    estimatedTime?: string;
    body?: string;
};

export type LessonProgressItem = {
    id?: string;
    title?: string;
    order?: number;
    completed?: boolean;
};

export type Document = {
    id?: string;
    title?: string;
    url?: string;
    kind?: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
    tags?: Array<string>;
    updatedAt?: string;
    bookmarked?: boolean;
};

export type Tag = {
    id?: string;
    name?: string;
    color?: 'accent' | 'info' | 'warn' | 'danger' | 'muted';
};

export type ExerciseSummary = {
    id?: string;
    title?: string;
    trackId?: string;
    track?: string;
    tag?: string;
    difficulty?: 'Beginner' | 'Intermediate' | 'Advanced';
    estimatedTime?: string;
    xp?: number;
    brief?: string;
    objectiveCount?: number;
    status?: 'pending' | 'submitted' | 'approved' | 'changes';
    prUrl?: string | null;
};

export type ExerciseDetail = {
    id?: string;
    title?: string;
    trackId?: string;
    track?: string;
    tag?: string;
    difficulty?: 'Beginner' | 'Intermediate' | 'Advanced';
    estimatedTime?: string;
    xp?: number;
    brief?: string;
    overview?: string;
    objectives?: Array<string>;
    steps?: Array<string>;
    resources?: Array<{
        id?: string;
        title?: string;
    }>;
    hint?: string;
    status?: string;
    prUrl?: string;
};

export type Submission = {
    id?: string;
    exerciseId?: string;
    userId?: string;
    prUrl?: string;
    status?: 'submitted' | 'approved' | 'changes';
    submittedAt?: string;
};

export type Item = {
    id?: string;
    user?: {
        id?: string;
        name?: string;
        avatarHue?: number;
    };
    exercise?: string;
    prUrl?: string;
    status?: string;
    submittedAt?: string;
};

export type SubmissionFeedItem = {
    id?: string;
    user?: {
        id?: string;
        name?: string;
        avatarHue?: number;
    };
    exercise?: string;
    prUrl?: string;
    status?: string;
    submittedAt?: string;
};

export type SubmissionDetail = {
    id?: string;
    exerciseId?: string;
    exercise?: string;
    user?: {
        id?: string;
        name?: string;
    };
    prUrl?: string;
    status?: string;
    reviewerId?: string | null;
    reviewNote?: string | null;
    submittedAt?: string;
    reviewedAt?: string | null;
};

export type SubmissionHistoryResponse = {
    submissionId?: string;
    exerciseId?: string;
    history?: Array<SubmissionHistoryItem>;
};

export type SubmissionHistoryItem = {
    id?: string;
    prUrl?: string;
    status?: 'submitted' | 'approved' | 'changes';
    submittedAt?: string;
    reviewerId?: string | null;
    reviewNote?: string | null;
    reviewedAt?: string | null;
};

export type Notification = {
    id?: string;
    type?: 'submission_reviewed' | 'track_unlocked';
    title?: string;
    body?: string;
    read?: boolean;
    createdAt?: string;
};

export type LeaderboardEntry = {
    userId?: string;
    name?: string;
    level?: number;
    xp?: number;
    streakDays?: number;
    rank?: number;
};

export type PostAuthRegisterData = {
    body: {
        name: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Dữ liệu đầu vào không hợp lệ (lỗi validate DTO).
     */
    400: {
        statusCode?: number;
        message?: Array<string>;
        error?: string;
    };
    /**
     * Email đã được sử dụng.
     */
    409: ErrorResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Đăng ký thành công và tự động tạo phiên đăng nhập.
     */
    201: {
        user?: User;
        accessToken?: string;
        refreshToken?: string;
        /**
         * Thời hạn token tính bằng giây (ví dụ 900 = 15 phút).
         */
        expiresIn?: number;
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body: {
        email: string;
        password: string;
        rememberMe?: boolean;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Sai thông tin đăng nhập.
     */
    401: ErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Đăng nhập thành công.
     */
    200: {
        user?: User;
        accessToken?: string;
        refreshToken?: string;
        expiresIn?: number;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthGoogleData = {
    body: {
        idToken: string;
    };
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type PostAuthGoogleErrors = {
    /**
     * Dữ liệu đầu vào không hợp lệ (lỗi validate DTO).
     */
    400: {
        statusCode?: number;
        message?: Array<string>;
        error?: string;
    };
};

export type PostAuthGoogleError = PostAuthGoogleErrors[keyof PostAuthGoogleErrors];

export type PostAuthGoogleResponses = {
    /**
     * Xác thực Google thành công. Trả về thông tin phiên giống như `/auth/login`.
     */
    200: {
        user?: User;
        accessToken?: string;
        refreshToken?: string;
        expiresIn?: number;
    };
};

export type PostAuthGoogleResponse = PostAuthGoogleResponses[keyof PostAuthGoogleResponses];

export type PostAuthRefreshData = {
    body: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Refresh token không hợp lệ hoặc đã hết hạn.
     */
    401: ErrorResponse;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * Cấp token mới thành công.
     */
    200: {
        accessToken?: string;
        refreshToken?: string;
        expiresIn?: number;
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Đăng xuất thành công. Không có dữ liệu trả về.
     */
    204: void;
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthForgotPasswordData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type PostAuthForgotPasswordResponses = {
    /**
     * Yêu cầu đã được tiếp nhận.
     */
    202: {
        message?: string;
    };
};

export type PostAuthForgotPasswordResponse = PostAuthForgotPasswordResponses[keyof PostAuthForgotPasswordResponses];

export type PostAuthResetPasswordData = {
    body: {
        token: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Dữ liệu đầu vào không hợp lệ (lỗi validate DTO).
     */
    400: {
        statusCode?: number;
        message?: Array<string>;
        error?: string;
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Đổi mật khẩu thành công.
     */
    200: {
        message?: string;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * Thành công.
     */
    200: UserDetail;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc danh sách theo Cohort ID
         */
        cohortId?: string;
        /**
         * Lọc theo vai trò (learner hoặc admin)
         */
        role?: 'learner' | 'admin';
        /**
         * Tìm kiếm theo họ tên hoặc email
         */
        q?: string;
        /**
         * Giới hạn số lượng bản ghi trả về (tối đa 50)
         */
        limit?: number;
        /**
         * Cursor phục vụ phân trang danh sách
         */
        cursor?: string;
    };
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<UserSummary>;
        nextCursor?: string | null;
        hasMore?: boolean;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        /**
         * ID của người dùng cần xem
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không đủ quyền truy cập (Learner xem profile người khác).
     */
    403: ErrorResponse;
    /**
     * Không tìm thấy người dùng.
     */
    404: ErrorResponse;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
    /**
     * Thành công.
     */
    200: UserDetail;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PatchUsersMeData = {
    body: {
        title?: string;
        avatarHue?: number;
    };
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PatchUsersMeErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PatchUsersMeError = PatchUsersMeErrors[keyof PatchUsersMeErrors];

export type PatchUsersMeResponses = {
    /**
     * Cập nhật thành công.
     */
    200: {
        id?: string;
        title?: string;
        avatarHue?: number;
    };
};

export type PatchUsersMeResponse = PatchUsersMeResponses[keyof PatchUsersMeResponses];

export type GetUsersMeStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/stats';
};

export type GetUsersMeStatsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetUsersMeStatsError = GetUsersMeStatsErrors[keyof GetUsersMeStatsErrors];

export type GetUsersMeStatsResponses = {
    /**
     * Thành công.
     */
    200: UserDashboardStats;
};

export type GetUsersMeStatsResponse = GetUsersMeStatsResponses[keyof GetUsersMeStatsResponses];

export type PostUsersMeNotificationsSlackData = {
    body: {
        /**
         * ID định danh của user trên workspace Slack
         */
        slackMemberId: string;
    };
    path?: never;
    query?: never;
    url: '/users/me/notifications/slack';
};

export type PostUsersMeNotificationsSlackErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PostUsersMeNotificationsSlackError = PostUsersMeNotificationsSlackErrors[keyof PostUsersMeNotificationsSlackErrors];

export type PostUsersMeNotificationsSlackResponses = {
    /**
     * Liên kết thành công.
     */
    200: {
        userId?: string;
        slackMemberId?: string;
        slackNotificationsEnabled?: boolean;
    };
};

export type PostUsersMeNotificationsSlackResponse = PostUsersMeNotificationsSlackResponses[keyof PostUsersMeNotificationsSlackResponses];

export type GetCohortsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cohorts';
};

export type GetCohortsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetCohortsError = GetCohortsErrors[keyof GetCohortsErrors];

export type GetCohortsResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<CohortSummary>;
        nextCursor?: string | null;
        hasMore?: boolean;
    };
};

export type GetCohortsResponse = GetCohortsResponses[keyof GetCohortsResponses];

export type PostCohortsData = {
    body: {
        /**
         * Tên khóa học
         */
        name: string;
        /**
         * Số ngày mục tiêu để hoàn thành lộ trình
         */
        targetRampDays?: number;
    };
    path?: never;
    query?: never;
    url: '/cohorts';
};

export type PostCohortsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PostCohortsError = PostCohortsErrors[keyof PostCohortsErrors];

export type PostCohortsResponses = {
    /**
     * Tạo thành công.
     */
    201: CohortDetail;
};

export type PostCohortsResponse = PostCohortsResponses[keyof PostCohortsResponses];

export type GetCohortsByIdData = {
    body?: never;
    path: {
        /**
         * ID của Cohort
         */
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}';
};

export type GetCohortsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy Cohort.
     */
    404: ErrorResponse;
};

export type GetCohortsByIdError = GetCohortsByIdErrors[keyof GetCohortsByIdErrors];

export type GetCohortsByIdResponses = {
    /**
     * Thành công.
     */
    200: CohortDetail;
};

export type GetCohortsByIdResponse = GetCohortsByIdResponses[keyof GetCohortsByIdResponses];

export type PatchCohortsByIdData = {
    body: {
        name?: string;
        targetRampDays?: number;
    };
    path: {
        /**
         * ID của Cohort cần sửa
         */
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}';
};

export type PatchCohortsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PatchCohortsByIdError = PatchCohortsByIdErrors[keyof PatchCohortsByIdErrors];

export type PatchCohortsByIdResponses = {
    /**
     * Cập nhật thành công.
     */
    200: CohortDetail;
};

export type PatchCohortsByIdResponse = PatchCohortsByIdResponses[keyof PatchCohortsByIdResponses];

export type GetCohortsByIdOverviewData = {
    body?: never;
    path: {
        /**
         * ID của Cohort
         */
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}/overview';
};

export type GetCohortsByIdOverviewErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetCohortsByIdOverviewError = GetCohortsByIdOverviewErrors[keyof GetCohortsByIdOverviewErrors];

export type GetCohortsByIdOverviewResponses = {
    /**
     * Thành công.
     */
    200: CohortDashboardStats;
};

export type GetCohortsByIdOverviewResponse = GetCohortsByIdOverviewResponses[keyof GetCohortsByIdOverviewResponses];

export type GetCohortsByIdTrackCompletionData = {
    body?: never;
    path: {
        /**
         * ID của Cohort
         */
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}/track-completion';
};

export type GetCohortsByIdTrackCompletionErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetCohortsByIdTrackCompletionError = GetCohortsByIdTrackCompletionErrors[keyof GetCohortsByIdTrackCompletionErrors];

export type GetCohortsByIdTrackCompletionResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<{
            trackId?: string;
            title?: string;
            completionPct?: number;
        }>;
    };
};

export type GetCohortsByIdTrackCompletionResponse = GetCohortsByIdTrackCompletionResponses[keyof GetCohortsByIdTrackCompletionResponses];

export type GetCohortsByIdExportData = {
    body?: never;
    path: {
        /**
         * ID của Cohort
         */
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}/export';
};

export type GetCohortsByIdExportErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetCohortsByIdExportError = GetCohortsByIdExportErrors[keyof GetCohortsByIdExportErrors];

export type GetCohortsByIdExportResponses = {
    /**
     * File CSV được sinh thành công.
     */
    200: string;
};

export type GetCohortsByIdExportResponse = GetCohortsByIdExportResponses[keyof GetCohortsByIdExportResponses];

export type GetTracksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Trang hiện tại (mặc định 1)
         */
        page?: number;
        /**
         * Số lượng chặng trên mỗi trang (mặc định 20, tối đa 50)
         */
        limit?: number;
    };
    url: '/tracks';
};

export type GetTracksErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetTracksError = GetTracksErrors[keyof GetTracksErrors];

export type GetTracksResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<TrackSummary>;
        meta?: {
            total?: number;
            page?: number;
            limit?: number;
            lastPage?: number;
        };
    };
};

export type GetTracksResponse = GetTracksResponses[keyof GetTracksResponses];

export type PostTracksData = {
    body: {
        title: string;
        description: string;
        estimatedTime: string;
        lessonCount: number;
        /**
         * Chèn sau Track có ID này (để tự động tính toán order). Nếu bỏ trống sẽ chèn cuối cùng.
         */
        afterTrackId?: string;
    };
    path?: never;
    query?: never;
    url: '/tracks';
};

export type PostTracksErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PostTracksError = PostTracksErrors[keyof PostTracksErrors];

export type PostTracksResponses = {
    /**
     * Tạo thành công.
     */
    201: TrackDetail;
};

export type PostTracksResponse = PostTracksResponses[keyof PostTracksResponses];

export type PatchTracksReorderData = {
    body: {
        /**
         * Danh sách ID của track được sắp xếp lại.
         */
        order: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/tracks/reorder';
};

export type PatchTracksReorderErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PatchTracksReorderError = PatchTracksReorderErrors[keyof PatchTracksReorderErrors];

export type PatchTracksReorderResponses = {
    /**
     * Đã cập nhật thứ tự thành công.
     */
    200: {
        message?: string;
        count?: number;
    };
};

export type PatchTracksReorderResponse = PatchTracksReorderResponses[keyof PatchTracksReorderResponses];

export type DeleteTracksByIdData = {
    body?: never;
    path: {
        /**
         * ID của Track cần xóa
         */
        id: string;
    };
    query?: never;
    url: '/tracks/{id}';
};

export type DeleteTracksByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type DeleteTracksByIdError = DeleteTracksByIdErrors[keyof DeleteTracksByIdErrors];

export type DeleteTracksByIdResponses = {
    /**
     * Xóa thành công.
     */
    204: void;
};

export type DeleteTracksByIdResponse = DeleteTracksByIdResponses[keyof DeleteTracksByIdResponses];

export type GetTracksByIdData = {
    body?: never;
    path: {
        /**
         * ID của Track
         */
        id: string;
    };
    query?: never;
    url: '/tracks/{id}';
};

export type GetTracksByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy Track.
     */
    404: ErrorResponse;
};

export type GetTracksByIdError = GetTracksByIdErrors[keyof GetTracksByIdErrors];

export type GetTracksByIdResponses = {
    /**
     * Thành công.
     */
    200: TrackDetail;
};

export type GetTracksByIdResponse = GetTracksByIdResponses[keyof GetTracksByIdResponses];

export type PatchTracksByIdData = {
    body: {
        title?: string;
        description?: string;
        estimatedTime?: string;
        icon?: string;
    };
    path: {
        /**
         * ID của Track
         */
        id: string;
    };
    query?: never;
    url: '/tracks/{id}';
};

export type PatchTracksByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type PatchTracksByIdError = PatchTracksByIdErrors[keyof PatchTracksByIdErrors];

export type PatchTracksByIdResponses = {
    /**
     * Cập nhật thành công.
     */
    200: TrackDetail;
};

export type PatchTracksByIdResponse = PatchTracksByIdResponses[keyof PatchTracksByIdResponses];

export type GetTracksByIdLessonsData = {
    body?: never;
    path: {
        /**
         * ID của Track
         */
        id: string;
    };
    query?: never;
    url: '/tracks/{id}/lessons';
};

export type GetTracksByIdLessonsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy Track.
     */
    404: ErrorResponse;
};

export type GetTracksByIdLessonsError = GetTracksByIdLessonsErrors[keyof GetTracksByIdLessonsErrors];

export type GetTracksByIdLessonsResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<LessonSummary>;
    };
};

export type GetTracksByIdLessonsResponse = GetTracksByIdLessonsResponses[keyof GetTracksByIdLessonsResponses];

export type PostTracksByIdLessonsData = {
    body: {
        title: string;
        /**
         * Số thứ tự sắp xếp bài học trong Track
         */
        order: number;
        estimatedTime: string;
        /**
         * Nội dung bài học (hỗ trợ định dạng Markdown)
         */
        body: string;
    };
    path: {
        /**
         * ID của Track cần thêm bài học
         */
        id: string;
    };
    query?: never;
    url: '/tracks/{id}/lessons';
};

export type PostTracksByIdLessonsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PostTracksByIdLessonsError = PostTracksByIdLessonsErrors[keyof PostTracksByIdLessonsErrors];

export type PostTracksByIdLessonsResponses = {
    /**
     * Tạo thành công.
     */
    201: LessonDetail;
};

export type PostTracksByIdLessonsResponse = PostTracksByIdLessonsResponses[keyof PostTracksByIdLessonsResponses];

export type DeleteLessonsByIdData = {
    body?: never;
    path: {
        /**
         * ID của bài học cần xóa
         */
        id: string;
    };
    query?: never;
    url: '/lessons/{id}';
};

export type DeleteLessonsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type DeleteLessonsByIdError = DeleteLessonsByIdErrors[keyof DeleteLessonsByIdErrors];

export type DeleteLessonsByIdResponses = {
    /**
     * Xóa thành công.
     */
    204: void;
};

export type DeleteLessonsByIdResponse = DeleteLessonsByIdResponses[keyof DeleteLessonsByIdResponses];

export type PatchLessonsByIdData = {
    body: {
        title?: string;
        body?: string;
        estimatedTime?: string;
    };
    path: {
        /**
         * ID của bài học
         */
        id: string;
    };
    query?: never;
    url: '/lessons/{id}';
};

export type PatchLessonsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy bài học.
     */
    404: ErrorResponse;
};

export type PatchLessonsByIdError = PatchLessonsByIdErrors[keyof PatchLessonsByIdErrors];

export type PatchLessonsByIdResponses = {
    /**
     * Cập nhật thành công.
     */
    200: LessonDetail;
};

export type PatchLessonsByIdResponse = PatchLessonsByIdResponses[keyof PatchLessonsByIdResponses];

export type PostLessonsByIdCompleteData = {
    body?: never;
    path: {
        /**
         * ID của bài học cần hoàn thành
         */
        id: string;
    };
    query?: never;
    url: '/lessons/{id}/complete';
};

export type PostLessonsByIdCompleteErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy bài học.
     */
    404: ErrorResponse;
};

export type PostLessonsByIdCompleteError = PostLessonsByIdCompleteErrors[keyof PostLessonsByIdCompleteErrors];

export type PostLessonsByIdCompleteResponses = {
    /**
     * Đánh dấu thành công.
     */
    200: {
        lessonId?: string;
        trackId?: string;
        /**
         * Số lượng bài học đã xong trong track này
         */
        lessonsCompleted?: number;
        trackStatus?: 'completed' | 'in_progress' | 'locked';
        /**
         * XP nhận được từ bài học này
         */
        xpAwarded?: number;
        /**
         * Tổng điểm XP hiện tại của người dùng
         */
        totalXp?: number;
        /**
         * ID của Track tiếp theo vừa được mở khóa (nếu hoàn tất track hiện tại)
         */
        unlockedTrackId?: string | null;
    };
};

export type PostLessonsByIdCompleteResponse = PostLessonsByIdCompleteResponses[keyof PostLessonsByIdCompleteResponses];

export type GetDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Từ khóa tìm kiếm trong tiêu đề
         */
        q?: string;
        /**
         * Lọc danh sách tag phân tách bằng dấu phẩy
         */
        tags?: string;
        /**
         * Lọc theo phân loại tài liệu
         */
        kind?: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
        /**
         * Số bản ghi tối đa trả về
         */
        limit?: number;
        /**
         * Con trỏ phục vụ phân trang
         */
        cursor?: string;
    };
    url: '/documents';
};

export type GetDocumentsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetDocumentsError = GetDocumentsErrors[keyof GetDocumentsErrors];

export type GetDocumentsResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<Document>;
        nextCursor?: string | null;
        hasMore?: boolean;
    };
};

export type GetDocumentsResponse = GetDocumentsResponses[keyof GetDocumentsResponses];

export type PostDocumentsData = {
    body: {
        title: string;
        /**
         * URL đường dẫn tài liệu (đối với wiki nội bộ hoặc external)
         */
        url: string;
        kind: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
        tags?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/documents';
};

export type PostDocumentsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PostDocumentsError = PostDocumentsErrors[keyof PostDocumentsErrors];

export type PostDocumentsResponses = {
    /**
     * Tạo thành công.
     */
    201: Document;
};

export type PostDocumentsResponse = PostDocumentsResponses[keyof PostDocumentsResponses];

export type GetDocumentsRecentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents/recent';
};

export type GetDocumentsRecentErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetDocumentsRecentError = GetDocumentsRecentErrors[keyof GetDocumentsRecentErrors];

export type GetDocumentsRecentResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<{
            id?: string;
            title?: string;
            tags?: Array<string>;
        }>;
    };
};

export type GetDocumentsRecentResponse = GetDocumentsRecentResponses[keyof GetDocumentsRecentResponses];

export type DeleteDocumentsByIdData = {
    body?: never;
    path: {
        /**
         * ID tài liệu cần xóa
         */
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type DeleteDocumentsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type DeleteDocumentsByIdError = DeleteDocumentsByIdErrors[keyof DeleteDocumentsByIdErrors];

export type DeleteDocumentsByIdResponses = {
    /**
     * Xóa thành công.
     */
    204: void;
};

export type DeleteDocumentsByIdResponse = DeleteDocumentsByIdResponses[keyof DeleteDocumentsByIdResponses];

export type GetDocumentsByIdData = {
    body?: never;
    path: {
        /**
         * ID của tài liệu
         */
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type GetDocumentsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy tài liệu.
     */
    404: ErrorResponse;
};

export type GetDocumentsByIdError = GetDocumentsByIdErrors[keyof GetDocumentsByIdErrors];

export type GetDocumentsByIdResponses = {
    /**
     * Thành công.
     */
    200: Document;
};

export type GetDocumentsByIdResponse = GetDocumentsByIdResponses[keyof GetDocumentsByIdResponses];

export type PatchDocumentsByIdData = {
    body: {
        title?: string;
        url?: string;
        kind?: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
        tags?: Array<string>;
    };
    path: {
        /**
         * ID của tài liệu
         */
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type PatchDocumentsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type PatchDocumentsByIdError = PatchDocumentsByIdErrors[keyof PatchDocumentsByIdErrors];

export type PatchDocumentsByIdResponses = {
    /**
     * Cập nhật thành công.
     */
    200: Document;
};

export type PatchDocumentsByIdResponse = PatchDocumentsByIdResponses[keyof PatchDocumentsByIdResponses];

export type DeleteDocumentsByIdBookmarkData = {
    body?: never;
    path: {
        /**
         * ID tài liệu
         */
        id: string;
    };
    query?: never;
    url: '/documents/{id}/bookmark';
};

export type DeleteDocumentsByIdBookmarkErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type DeleteDocumentsByIdBookmarkError = DeleteDocumentsByIdBookmarkErrors[keyof DeleteDocumentsByIdBookmarkErrors];

export type DeleteDocumentsByIdBookmarkResponses = {
    /**
     * Bỏ bookmark thành công. Không có body trả về.
     */
    204: void;
};

export type DeleteDocumentsByIdBookmarkResponse = DeleteDocumentsByIdBookmarkResponses[keyof DeleteDocumentsByIdBookmarkResponses];

export type PostDocumentsByIdBookmarkData = {
    body?: never;
    path: {
        /**
         * ID tài liệu
         */
        id: string;
    };
    query?: never;
    url: '/documents/{id}/bookmark';
};

export type PostDocumentsByIdBookmarkErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type PostDocumentsByIdBookmarkError = PostDocumentsByIdBookmarkErrors[keyof PostDocumentsByIdBookmarkErrors];

export type PostDocumentsByIdBookmarkResponses = {
    /**
     * Đã đánh dấu bookmark thành công.
     */
    200: {
        documentId?: string;
        bookmarked?: boolean;
    };
};

export type PostDocumentsByIdBookmarkResponse = PostDocumentsByIdBookmarkResponses[keyof PostDocumentsByIdBookmarkResponses];

export type GetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tags';
};

export type GetTagsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetTagsError = GetTagsErrors[keyof GetTagsErrors];

export type GetTagsResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<Tag>;
    };
};

export type GetTagsResponse = GetTagsResponses[keyof GetTagsResponses];

export type PostTagsData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/tags';
};

export type PostTagsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Tag đã tồn tại trong hệ thống.
     */
    409: ErrorResponse;
};

export type PostTagsError = PostTagsErrors[keyof PostTagsErrors];

export type PostTagsResponses = {
    /**
     * Tạo thành công.
     */
    201: Tag;
};

export type PostTagsResponse = PostTagsResponses[keyof PostTagsResponses];

export type DeleteTagsByIdData = {
    body?: never;
    path: {
        /**
         * ID của tag cần xóa
         */
        id: string;
    };
    query?: never;
    url: '/tags/{id}';
};

export type DeleteTagsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy tag.
     */
    404: ErrorResponse;
};

export type DeleteTagsByIdError = DeleteTagsByIdErrors[keyof DeleteTagsByIdErrors];

export type DeleteTagsByIdResponses = {
    /**
     * Xóa thành công.
     */
    204: void;
};

export type DeleteTagsByIdResponse = DeleteTagsByIdResponses[keyof DeleteTagsByIdResponses];

export type GetExercisesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc bài tập thuộc Track cụ thể
         */
        trackId?: string;
        /**
         * Lọc theo nhãn chuyên môn (ví dụ NestJS)
         */
        tag?: string;
        /**
         * Lọc theo cấp độ khó
         */
        difficulty?: 'Beginner' | 'Intermediate' | 'Advanced';
        /**
         * Lọc theo trạng thái bài nộp cá nhân
         */
        status?: 'pending' | 'submitted' | 'approved' | 'changes';
    };
    url: '/exercises';
};

export type GetExercisesErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetExercisesError = GetExercisesErrors[keyof GetExercisesErrors];

export type GetExercisesResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<ExerciseSummary>;
        nextCursor?: string | null;
        hasMore?: boolean;
    };
};

export type GetExercisesResponse = GetExercisesResponses[keyof GetExercisesResponses];

export type PostExercisesData = {
    body: {
        title: string;
        /**
         * ID của track chứa bài tập này
         */
        trackId: string;
        /**
         * Tag phân loại chuyên môn
         */
        tag: string;
        difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
        estimatedTime: string;
        /**
         * Điểm kinh nghiệm nhận được khi hoàn tất bài tập
         */
        xp: number;
        brief: string;
        overview: string;
        /**
         * Tiêu chí nghiệm thu (Acceptance Criteria)
         */
        objectives: Array<string>;
        /**
         * Các bước thực hiện gợi ý
         */
        steps: Array<string>;
        /**
         * Danh sách ID tài liệu tham khảo
         */
        resourceDocIds?: Array<string>;
        hint?: string;
    };
    path?: never;
    query?: never;
    url: '/exercises';
};

export type PostExercisesErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PostExercisesError = PostExercisesErrors[keyof PostExercisesErrors];

export type PostExercisesResponses = {
    /**
     * Tạo thành công.
     */
    201: {
        id?: string;
        title?: string;
        trackId?: string;
        xp?: number;
        status?: string;
    };
};

export type PostExercisesResponse = PostExercisesResponses[keyof PostExercisesResponses];

export type DeleteExercisesByIdData = {
    body?: never;
    path: {
        /**
         * ID của bài tập
         */
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type DeleteExercisesByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type DeleteExercisesByIdError = DeleteExercisesByIdErrors[keyof DeleteExercisesByIdErrors];

export type DeleteExercisesByIdResponses = {
    /**
     * Xóa thành công.
     */
    204: void;
};

export type DeleteExercisesByIdResponse = DeleteExercisesByIdResponses[keyof DeleteExercisesByIdResponses];

export type GetExercisesByIdData = {
    body?: never;
    path: {
        /**
         * ID của bài tập
         */
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type GetExercisesByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy bài tập.
     */
    404: ErrorResponse;
};

export type GetExercisesByIdError = GetExercisesByIdErrors[keyof GetExercisesByIdErrors];

export type GetExercisesByIdResponses = {
    /**
     * Thành công.
     */
    200: ExerciseDetail;
};

export type GetExercisesByIdResponse = GetExercisesByIdResponses[keyof GetExercisesByIdResponses];

export type PatchExercisesByIdData = {
    body: {
        xp?: number;
        difficulty?: 'Beginner' | 'Intermediate' | 'Advanced';
    };
    path: {
        /**
         * ID của bài tập
         */
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type PatchExercisesByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy bài tập.
     */
    404: ErrorResponse;
};

export type PatchExercisesByIdError = PatchExercisesByIdErrors[keyof PatchExercisesByIdErrors];

export type PatchExercisesByIdResponses = {
    /**
     * Cập nhật thành công.
     */
    200: {
        id?: string;
        xp?: number;
        difficulty?: string;
    };
};

export type PatchExercisesByIdResponse = PatchExercisesByIdResponses[keyof PatchExercisesByIdResponses];

export type PostExercisesByIdSubmissionsData = {
    body: {
        /**
         * URL của Pull Request GitHub chứa bài giải
         */
        prUrl: string;
    };
    path: {
        /**
         * ID của bài tập
         */
        id: string;
    };
    query?: never;
    url: '/exercises/{id}/submissions';
};

export type PostExercisesByIdSubmissionsErrors = {
    /**
     * Dữ liệu đầu vào không hợp lệ (lỗi validate DTO).
     */
    400: {
        statusCode?: number;
        message?: Array<string>;
        error?: string;
    };
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy bài tập.
     */
    404: ErrorResponse;
};

export type PostExercisesByIdSubmissionsError = PostExercisesByIdSubmissionsErrors[keyof PostExercisesByIdSubmissionsErrors];

export type PostExercisesByIdSubmissionsResponses = {
    /**
     * Nộp bài thành công.
     */
    201: Submission;
};

export type PostExercisesByIdSubmissionsResponse = PostExercisesByIdSubmissionsResponses[keyof PostExercisesByIdSubmissionsResponses];

export type PutExercisesByIdSubmissionsData = {
    body: {
        prUrl: string;
    };
    path: {
        /**
         * ID bài tập
         */
        id: string;
    };
    query?: never;
    url: '/exercises/{id}/submissions';
};

export type PutExercisesByIdSubmissionsErrors = {
    /**
     * Dữ liệu đầu vào không hợp lệ (lỗi validate DTO).
     */
    400: {
        statusCode?: number;
        message?: Array<string>;
        error?: string;
    };
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PutExercisesByIdSubmissionsError = PutExercisesByIdSubmissionsErrors[keyof PutExercisesByIdSubmissionsErrors];

export type PutExercisesByIdSubmissionsResponses = {
    /**
     * Cập nhật bài nộp thành công.
     */
    200: Submission;
};

export type PutExercisesByIdSubmissionsResponse = PutExercisesByIdSubmissionsResponses[keyof PutExercisesByIdSubmissionsResponses];

export type GetSubmissionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc theo trạng thái bài nộp
         */
        status?: 'submitted' | 'approved' | 'changes';
        /**
         * Lọc bài nộp của học viên trong cohort cụ thể
         */
        cohortId?: string;
        /**
         * Giới hạn bản ghi trả về
         */
        limit?: number;
        /**
         * Cursor phân trang danh sách
         */
        cursor?: string;
    };
    url: '/submissions';
};

export type GetSubmissionsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetSubmissionsError = GetSubmissionsErrors[keyof GetSubmissionsErrors];

export type GetSubmissionsResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<SubmissionFeedItem>;
        nextCursor?: string | null;
        hasMore?: boolean;
    };
};

export type GetSubmissionsResponse = GetSubmissionsResponses[keyof GetSubmissionsResponses];

export type GetSubmissionsMineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/submissions/mine';
};

export type GetSubmissionsMineErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetSubmissionsMineError = GetSubmissionsMineErrors[keyof GetSubmissionsMineErrors];

export type GetSubmissionsMineResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<{
            id?: string;
            exerciseId?: string;
            exercise?: string;
            prUrl?: string;
            status?: 'submitted' | 'approved' | 'changes';
            submittedAt?: string;
        }>;
    };
};

export type GetSubmissionsMineResponse = GetSubmissionsMineResponses[keyof GetSubmissionsMineResponses];

export type GetSubmissionsByIdData = {
    body?: never;
    path: {
        /**
         * ID của bài nộp (Submission ID)
         */
        id: string;
    };
    query?: never;
    url: '/submissions/{id}';
};

export type GetSubmissionsByIdErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy bài nộp.
     */
    404: ErrorResponse;
};

export type GetSubmissionsByIdError = GetSubmissionsByIdErrors[keyof GetSubmissionsByIdErrors];

export type GetSubmissionsByIdResponses = {
    /**
     * Thành công.
     */
    200: SubmissionDetail;
};

export type GetSubmissionsByIdResponse = GetSubmissionsByIdResponses[keyof GetSubmissionsByIdResponses];

export type PostSubmissionsByIdApproveData = {
    body?: {
        /**
         * Nhận xét phê duyệt từ Admin
         */
        note?: string;
    };
    path: {
        /**
         * ID của bài nộp
         */
        id: string;
    };
    query?: never;
    url: '/submissions/{id}/approve';
};

export type PostSubmissionsByIdApproveErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy.
     */
    404: ErrorResponse;
};

export type PostSubmissionsByIdApproveError = PostSubmissionsByIdApproveErrors[keyof PostSubmissionsByIdApproveErrors];

export type PostSubmissionsByIdApproveResponses = {
    /**
     * Phê duyệt thành công.
     */
    200: {
        id?: string;
        status?: string;
        exerciseId?: string;
        exerciseStatus?: string;
        reviewerId?: string;
        reviewedAt?: string;
        xpAwarded?: number;
        learnerTotalXp?: number;
    };
};

export type PostSubmissionsByIdApproveResponse = PostSubmissionsByIdApproveResponses[keyof PostSubmissionsByIdApproveResponses];

export type PostSubmissionsByIdRequestChangesData = {
    body: {
        /**
         * Nội dung chi tiết các yêu cầu học viên cần chỉnh sửa
         */
        note: string;
    };
    path: {
        /**
         * ID bài nộp
         */
        id: string;
    };
    query?: never;
    url: '/submissions/{id}/request-changes';
};

export type PostSubmissionsByIdRequestChangesErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Người dùng không có quyền truy cập chức năng này (sai role).
     */
    403: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type PostSubmissionsByIdRequestChangesError = PostSubmissionsByIdRequestChangesErrors[keyof PostSubmissionsByIdRequestChangesErrors];

export type PostSubmissionsByIdRequestChangesResponses = {
    /**
     * Yêu cầu sửa đổi thành công.
     */
    200: {
        id?: string;
        status?: string;
        exerciseId?: string;
        exerciseStatus?: string;
        reviewerId?: string;
        reviewNote?: string;
        reviewedAt?: string;
    };
};

export type PostSubmissionsByIdRequestChangesResponse = PostSubmissionsByIdRequestChangesResponses[keyof PostSubmissionsByIdRequestChangesResponses];

export type GetSubmissionsByIdHistoryData = {
    body?: never;
    path: {
        /**
         * ID của bài nộp chính
         */
        id: string;
    };
    query?: never;
    url: '/submissions/{id}/history';
};

export type GetSubmissionsByIdHistoryErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy lịch sử.
     */
    404: ErrorResponse;
};

export type GetSubmissionsByIdHistoryError = GetSubmissionsByIdHistoryErrors[keyof GetSubmissionsByIdHistoryErrors];

export type GetSubmissionsByIdHistoryResponses = {
    /**
     * Thành công.
     */
    200: SubmissionHistoryResponse;
};

export type GetSubmissionsByIdHistoryResponse = GetSubmissionsByIdHistoryResponses[keyof GetSubmissionsByIdHistoryResponses];

export type GetSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Từ khóa tìm kiếm
         */
        q: string;
    };
    url: '/search';
};

export type GetSearchErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetSearchError = GetSearchErrors[keyof GetSearchErrors];

export type GetSearchResponses = {
    /**
     * Thành công.
     */
    200: {
        tracks?: Array<{
            id?: string;
            title?: string;
        }>;
        documents?: Array<{
            id?: string;
            title?: string;
            kind?: string;
        }>;
        exercises?: Array<{
            id?: string;
            title?: string;
            tag?: string;
        }>;
    };
};

export type GetSearchResponse = GetSearchResponses[keyof GetSearchResponses];

export type GetNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type GetNotificationsErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetNotificationsError = GetNotificationsErrors[keyof GetNotificationsErrors];

export type GetNotificationsResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<Notification>;
        /**
         * Số lượng thông báo chưa đọc
         */
        unreadCount?: number;
    };
};

export type GetNotificationsResponse = GetNotificationsResponses[keyof GetNotificationsResponses];

export type PostNotificationsByIdReadData = {
    body?: never;
    path: {
        /**
         * ID của thông báo cần đọc
         */
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type PostNotificationsByIdReadErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
    /**
     * Không tìm thấy thông báo.
     */
    404: ErrorResponse;
};

export type PostNotificationsByIdReadError = PostNotificationsByIdReadErrors[keyof PostNotificationsByIdReadErrors];

export type PostNotificationsByIdReadResponses = {
    /**
     * Cập nhật thành công.
     */
    200: {
        id?: string;
        read?: boolean;
    };
};

export type PostNotificationsByIdReadResponse = PostNotificationsByIdReadResponses[keyof PostNotificationsByIdReadResponses];

export type GetLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc bảng xếp hạng theo khóa học cụ thể. Nếu bỏ trống và scope là cohort, hệ thống tự động lấy cohort của học viên hiện tại.
         */
        cohortId?: string;
        /**
         * Phạm vi bảng xếp hạng (cohort hoặc global). Nếu chọn cohort và không truyền cohortId, hệ thống tự động lấy cohort của học viên hiện tại.
         */
        scope?: 'cohort' | 'global';
        /**
         * Số lượng học viên hiển thị tối đa trên bảng xếp hạng
         */
        limit?: number;
        /**
         * Con trỏ base64 dùng để phân trang dựa trên (level, xp, streakDays, createdAt, id)
         */
        cursor?: string;
    };
    url: '/leaderboard';
};

export type GetLeaderboardErrors = {
    /**
     * Chưa đăng nhập hoặc Token hết hạn/không hợp lệ.
     */
    401: {
        statusCode?: number;
        message?: string;
        error?: string;
    };
};

export type GetLeaderboardError = GetLeaderboardErrors[keyof GetLeaderboardErrors];

export type GetLeaderboardResponses = {
    /**
     * Thành công.
     */
    200: {
        data?: Array<LeaderboardEntry>;
        nextCursor?: string | null;
        hasMore?: boolean;
    };
};

export type GetLeaderboardResponse = GetLeaderboardResponses[keyof GetLeaderboardResponses];
