// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://be-teal-tau.vercel.app/api/v1' | (string & {});
};

export type UpdateProfileDto = {
    /**
     * The name of the user
     */
    name?: string;
    /**
     * The title of the user
     */
    title?: string;
    /**
     * The avatar hue of the user (0-360)
     */
    avatarHue?: number;
};

export type SubStatsDto = {
    completed: number;
    total: number;
};

export type ExerciseStatsDto = {
    approved: number;
    total: number;
    awaitingReview: number;
};

export type SavedDocsStatsDto = {
    total: number;
    unread: number;
};

export type UserDashboardStatsDto = {
    level: number;
    xp: number;
    xpThisWeek: number;
    streakDays: number;
    overallCompletion: number;
    tracks: SubStatsDto;
    exercises: ExerciseStatsDto;
    savedDocs: SavedDocsStatsDto;
};

export type CreateUserDto = {
    /**
     * Địa chỉ email.
     */
    email: string;
    /**
     * Họ tên người dùng.
     */
    name: string;
    /**
     * Mật khẩu khởi tạo.
     */
    password: string;
    /**
     * Vai trò người dùng.
     */
    role?: 'learner' | 'admin';
};

export type UpdateUserAdminDto = {
    /**
     * Vai trò mới của người dùng.
     */
    role?: 'learner' | 'admin';
    /**
     * ID của cohort gán cho người dùng (UUID, gửi null để hủy gán).
     */
    cohortId?: {
        [key: string]: unknown;
    } | null;
};

export type UpdateUserRoleDto = {
    /**
     * Vai trò mới của người dùng.
     */
    role: 'learner' | 'admin';
};

export type UpdateUserStatusDto = {
    /**
     * Trạng thái hoạt động của người dùng.
     */
    isActive: boolean;
};

export type BanUserDto = {
    /**
     * Lý do khóa tài khoản.
     */
    reason: string;
    /**
     * Thời hạn khóa tài khoản (nếu để trống hoặc null tức là khóa vĩnh viễn).
     */
    expiresAt?: {
        [key: string]: unknown;
    };
};

export type AssignCohortDto = {
    /**
     * ID của cohort (UUID) cần gán cho người dùng.
     */
    cohortId: string;
};

export type GoogleLoginDto = {
    /**
     * ID Token nhận được từ Google OAuth Client phía frontend.
     */
    idToken: string;
};

export type UserProfileDto = {
    id: string;
    email: string;
    name: string;
    role: 'learner' | 'admin';
    title: string | null;
    avatarHue: number;
    cohortId: string | null;
    cohort: {
        id?: string;
        name?: string;
    } | null;
    level: number;
    xp: number;
    /**
     * Số ngày streak hiện tại của user.
     */
    streakDays: number;
    joinedAt: string;
};

export type AuthResponseDto = {
    accessToken: string;
    refreshToken: string;
    user: UserProfileDto;
};

export type RegisterDto = {
    name: string;
    email: string;
    password: string;
};

export type LoginDto = {
    email: string;
    password: string;
    rememberMe?: boolean;
};

export type AuthTokensDto = {
    accessToken: string;
    refreshToken: string;
    /**
     * Access token lifetime in seconds.
     */
    expiresIn: number;
};

export type RefreshTokenDto = {
    /**
     * A valid, previously issued refresh token (JWT).
     */
    refreshToken: string;
};

export type ForgotPasswordDto = {
    /**
     * Email cần khôi phục mật khẩu.
     */
    email: string;
};

export type ForgotPasswordResponseDto = {
    /**
     * Trạng thái thành công
     */
    success: boolean;
    /**
     * Thông điệp phản hồi
     */
    message: string;
    /**
     * Token khôi phục mật khẩu (chỉ trả về ở dev/test hoặc cấu hình)
     */
    resetToken?: string;
    /**
     * Đường dẫn đặt lại mật khẩu
     */
    resetUrl?: string;
};

export type ResetPasswordDto = {
    /**
     * Mã token khôi phục mật khẩu nhận được từ email.
     */
    token: string;
    /**
     * Mật khẩu mới.
     */
    password: string;
};

export type ChangePasswordDto = {
    /**
     * Mật khẩu hiện tại.
     */
    currentPassword: string;
    /**
     * Mật khẩu mới.
     */
    newPassword: string;
};

export type CreateCohortDto = {
    /**
     * Tên của khóa học viên (Cohort).
     */
    name: string;
    /**
     * Số ngày mục tiêu để hoàn thành lộ trình onboarding.
     */
    targetRampDays: number;
};

export type CohortDetailDto = {
    /**
     * ID của Cohort
     */
    id: string;
    /**
     * Tên của Cohort
     */
    name: string;
    /**
     * Mục tiêu số ngày hoàn thành
     */
    targetRampDays: number;
    /**
     * Thời gian khởi tạo Cohort
     */
    createdAt: string;
};

export type CohortSummaryDto = {
    /**
     * ID của Cohort
     */
    id: string;
    /**
     * Tên của Cohort
     */
    name: string;
    /**
     * Số lượng học viên trong Cohort
     */
    learnerCount: number;
    /**
     * Tỷ lệ hoàn thành trung bình của Cohort
     */
    avgCompletion: number;
};

export type CohortMetaDto = {
    /**
     * Tổng số
     */
    total: number;
    /**
     * Trang hiện tại
     */
    page: number;
    /**
     * Giới hạn số phần tử
     */
    limit: number;
    /**
     * Trang cuối
     */
    lastPage: number;
};

export type CohortListResponseDto = {
    data: Array<CohortSummaryDto>;
    meta: CohortMetaDto;
};

export type CohortDashboardStatsDto = {
    /**
     * Số lượng học viên đang hoạt động
     */
    activeLearners: number;
    /**
     * Học viên mới trong tuần này
     */
    newThisWeek: number;
    /**
     * Tỷ lệ hoàn thành trung bình (phần trăm)
     */
    avgCompletion: number;
    /**
     * Độ lệch tỷ lệ hoàn thành trung bình so với tuần trước
     */
    avgCompletionDelta: number;
    /**
     * Số lượng bài tập đang chờ chấm
     */
    pendingReview: number;
    /**
     * Thời gian bài nộp chờ lâu nhất
     */
    oldestPendingAgo: string;
    /**
     * Số ngày hoàn thành trung bình (ramp days)
     */
    avgRampDays: number;
    /**
     * Mục tiêu hoàn thành của Cohort (ramp days)
     */
    targetRampDays: number;
};

export type CohortUserTrackProgressDto = {
    trackId: string;
    title: string;
    /**
     * Tỷ lệ hoàn thành track (%)
     */
    progressPct: number;
    completedLessons: number;
    totalLessons: number;
    status: 'not_started' | 'in_progress' | 'completed';
};

export type CohortUserProgressItemDto = {
    userId: string;
    name: string;
    email: string;
    avatarHue: {
        [key: string]: unknown;
    } | null;
    level: number;
    xp: number;
    tracks: Array<CohortUserTrackProgressDto>;
};

export type CohortUsersProgressResponseDto = {
    cohortId: string;
    /**
     * Tổng số học viên khớp bộ lọc
     */
    totalUsers: number;
    page: number;
    limit: number;
    data: Array<CohortUserProgressItemDto>;
};

export type CohortTrackCompletionItemDto = {
    /**
     * ID của Track
     */
    trackId: string;
    /**
     * Tiêu đề Track
     */
    title: string;
    /**
     * Tỷ lệ hoàn thành track của Cohort
     */
    completionPct: number;
};

export type CohortTrackCompletionResponseDto = {
    data: Array<CohortTrackCompletionItemDto>;
};

export type UpdateCohortDto = {
    /**
     * Tên của khóa học viên (Cohort).
     */
    name?: string;
    /**
     * Số ngày mục tiêu để hoàn thành lộ trình onboarding.
     */
    targetRampDays?: number;
    /**
     * Trạng thái hoạt động của Cohort.
     */
    isActive?: boolean;
};

export type TrackSummaryDto = {
    /**
     * ID của Track
     */
    id: string;
    /**
     * Tiêu đề Track
     */
    title: string;
    /**
     * Thời gian ước tính hoàn thành track
     */
    estimatedTime: string;
    /**
     * Thứ tự sắp xếp của track
     */
    order: number;
    /**
     * Tổng số bài học trong track
     */
    lessonCount: number;
    /**
     * Icon hiển thị của track
     */
    icon: string;
    /**
     * Trạng thái học tập của track đối với user
     */
    status: 'completed' | 'in_progress' | 'locked';
    /**
     * Số lượng bài học đã hoàn thành trong track
     */
    lessonsCompleted: number;
    /**
     * Mô tả chi tiết nội dung track
     */
    description: string;
    /**
     * Cấp độ khó của Track/Course
     */
    level: string;
    /**
     * Đường dẫn ảnh thumbnail của Track
     */
    thumbnail: {
        [key: string]: unknown;
    } | null;
    /**
     * Trạng thái truy cập của user đối với track
     */
    accessStatus: 'unlocked' | 'locked';
    /**
     * Lý do track bị khóa (nếu có)
     */
    lockedReason: {
        [key: string]: unknown;
    } | null;
    /**
     * ID của bài học tiếp theo cần học trong track
     */
    currentLessonId: {
        [key: string]: unknown;
    } | null;
};

export type TrackMetaDto = {
    /**
     * Tổng số tracks
     */
    total: number;
    /**
     * Trang hiện tại
     */
    page: number;
    /**
     * Số lượng phần tử trên mỗi trang
     */
    limit: number;
    /**
     * Tổng số trang
     */
    lastPage: number;
};

export type TrackListResponseDto = {
    data: Array<TrackSummaryDto>;
    meta: TrackMetaDto;
};

export type ReorderTracksDto = {
    /**
     * Danh sách ID (UUID) của các tracks được sắp xếp lại theo thứ tự mới.
     */
    order: Array<string>;
};

export type LessonProgressItemDto = {
    /**
     * ID của bài học
     */
    id: string;
    /**
     * Tiêu đề bài học
     */
    title: string;
    /**
     * Số thứ tự bài học trong track
     */
    order: number;
    /**
     * Trạng thái hoàn thành bài học
     */
    completed: boolean;
    /**
     * Phân loại bài học
     */
    type: 'video' | 'reading' | 'quiz' | 'coding' | 'assignment';
    /**
     * Mô tả ngắn của bài học
     */
    description: string | null;
    /**
     * Thời gian ước tính hoàn thành
     */
    estimatedTime: string;
};

export type TrackDetailDto = {
    /**
     * ID của Track
     */
    id: string;
    /**
     * Tiêu đề Track
     */
    title: string;
    /**
     * Thời gian ước tính hoàn thành track
     */
    estimatedTime: string;
    /**
     * Thứ tự sắp xếp của track
     */
    order: number;
    /**
     * Icon hiển thị của track
     */
    icon: string;
    /**
     * Trạng thái học tập của track đối với user
     */
    status: 'completed' | 'in_progress' | 'locked';
    /**
     * Số lượng bài học đã hoàn thành trong track
     */
    lessonsCompleted: number;
    /**
     * Mô tả chi tiết nội dung track
     */
    description: string;
    /**
     * Danh sách bài học trong track kèm trạng thái hoàn thành
     */
    lessons: Array<LessonProgressItemDto>;
    /**
     * Cấp độ khó của Track/Course
     */
    level: string;
    /**
     * Đường dẫn ảnh thumbnail của Track
     */
    thumbnail: {
        [key: string]: unknown;
    } | null;
    /**
     * Trạng thái truy cập của user đối với track
     */
    accessStatus: 'unlocked' | 'locked';
    /**
     * Lý do track bị khóa (nếu có)
     */
    lockedReason: {
        [key: string]: unknown;
    } | null;
    /**
     * ID của bài học tiếp theo cần học trong track
     */
    currentLessonId: {
        [key: string]: unknown;
    } | null;
    /**
     * Thông tin track phía trước
     */
    prevTrack: {
        [key: string]: unknown;
    } | null;
    /**
     * Thông tin track kế tiếp
     */
    nextTrack: {
        [key: string]: unknown;
    } | null;
};

export type CreateTrackDto = {
    /**
     * Tên lộ trình học (tiêu đề)
     */
    title: string;
    /**
     * Mô tả lộ trình học
     */
    description: string;
    /**
     * Thời gian ước tính
     */
    estimatedTime: string;
    /**
     * Số lượng bài học
     */
    lessonCount: number;
    /**
     * Chèn sau Track có ID này (để tự động tính toán order). Nếu bỏ trống sẽ chèn cuối cùng.
     */
    afterTrackId?: string;
    /**
     * Trạng thái lộ trình (GLI-94). Mặc định: Active.
     */
    status?: 'Developing' | 'Active' | 'Archived';
};

export type UpdateTrackDto = {
    /**
     * Tên lộ trình học (tiêu đề)
     */
    title?: string;
    /**
     * Mô tả lộ trình học
     */
    description?: string;
    /**
     * Thời gian ước tính
     */
    estimatedTime?: string;
    /**
     * Icon đại diện
     */
    icon?: string;
    /**
     * Trạng thái lộ trình (GLI-94)
     */
    status?: 'Developing' | 'Active' | 'Archived';
};

export type UpdateTrackProgressDto = {
    /**
     * Trạng thái tiến độ học của Track
     */
    status: 'not_started' | 'in_progress' | 'completed';
};

export type AdminTrackItemDto = {
    id: string;
    title: string;
    order: number;
    status: 'Developing' | 'Active' | 'Archived';
    level: string;
    estimatedTime: string;
    /**
     * Tổng số bài học trong track
     */
    totalLessons: number;
    /**
     * Số học viên đang tham gia track
     */
    enrolledCount: number;
    /**
     * Số học viên đã hoàn thành track
     */
    completedCount: number;
    /**
     * Tỷ lệ hoàn thành trung bình của học viên (%)
     */
    avgCompletion: number;
    createdAt: string;
    updatedAt: string;
};

export type AdminTrackListResponseDto = {
    data: Array<AdminTrackItemDto>;
};

export type LessonListResponseDto = {
    data: Array<LessonProgressItemDto>;
};

export type TagResponseDto = {
    /**
     * ID của tag
     */
    id: string;
    /**
     * Tên của tag
     */
    name: string;
};

export type DocumentResponseDto = {
    /**
     * ID của tài liệu kỹ thuật
     */
    id: string;
    /**
     * Tiêu đề tài liệu
     */
    title: string;
    /**
     * Nội dung chi tiết tài liệu (nếu có)
     */
    content: {
        [key: string]: unknown;
    } | null;
    /**
     * Đường dẫn liên kết tài liệu (nếu có)
     */
    url: {
        [key: string]: unknown;
    } | null;
    /**
     * Phân loại tài liệu
     */
    kind: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
    /**
     * Danh sách các tag của tài liệu
     */
    tags: Array<TagResponseDto>;
    /**
     * Trạng thái bookmark của user
     */
    isBookmarked: boolean;
};

export type LessonDetailDto = {
    /**
     * ID của bài học
     */
    id: string;
    /**
     * ID của track chứa bài học
     */
    trackId: string;
    /**
     * Tiêu đề bài học
     */
    title: string;
    /**
     * Số thứ tự bài học trong track
     */
    order: number;
    /**
     * Thời gian ước tính hoàn thành
     */
    estimatedTime: string;
    /**
     * Nội dung chi tiết bài học (Markdown)
     */
    body: string;
    /**
     * Mô tả ngắn của bài học
     */
    description: string | null;
    /**
     * Phân loại bài học
     */
    type: 'video' | 'reading' | 'quiz' | 'coding' | 'assignment';
    /**
     * Trạng thái hoàn thành bài học của user
     */
    completed: boolean;
    /**
     * Danh sách tài liệu liên quan đến bài học
     */
    relatedDocs: Array<DocumentResponseDto>;
};

export type ExerciseSummaryDto = {
    /**
     * ID của bài tập
     */
    id: string;
    /**
     * Tiêu đề bài tập
     */
    title: string;
    /**
     * ID của Track chứa bài tập
     */
    trackId: string;
    /**
     * Tiêu đề Track chứa bài tập
     */
    track: string;
    /**
     * Nhãn chuyên môn
     */
    tag: string;
    /**
     * Cấp độ khó
     */
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    /**
     * Thời gian ước tính hoàn thành
     */
    estimatedTime: string;
    /**
     * Số điểm XP thưởng khi hoàn thành
     */
    xp: number;
    /**
     * Tóm tắt yêu cầu bài tập
     */
    brief: string;
    /**
     * Số lượng mục tiêu cần hoàn thành
     */
    objectiveCount: number;
    /**
     * Trạng thái bài nộp cá nhân của user
     */
    status: 'pending' | 'submitted' | 'approved' | 'changes' | 'rejected';
    prUrl: string | null;
    lessonId: string | null;
    type: 'PR_REVIEW' | 'QUIZ' | 'FILL_IN_BLANK';
    isMandatory: boolean;
};

export type ExerciseListResponseDto = {
    data: Array<ExerciseSummaryDto>;
};

export type CreateLessonDto = {
    /**
     * Tiêu đề bài học
     */
    title: string;
    /**
     * Mô tả ngắn của bài học
     */
    description?: string | null;
    /**
     * Thứ tự của bài học trong lộ trình
     */
    order: number;
    /**
     * Thời gian ước tính hoàn thành bài học
     */
    estimatedTime: string;
    /**
     * Nội dung bài học
     */
    body: string;
};

export type UpdateLessonDto = {
    /**
     * Tiêu đề bài học
     */
    title?: string;
    /**
     * Mô tả ngắn của bài học
     */
    description?: string | null;
    /**
     * Thứ tự của bài học trong lộ trình
     */
    order?: number;
    /**
     * Thời gian ước tính hoàn thành bài học
     */
    estimatedTime?: string;
    /**
     * Nội dung bài học
     */
    body?: string;
};

export type CompleteLessonResponseDto = {
    /**
     * ID của bài học vừa hoàn thành
     */
    lessonId: string;
    /**
     * ID của track chứa bài học
     */
    trackId: string;
    /**
     * Số lượng bài học đã hoàn thành trong track
     */
    lessonsCompleted: number;
    /**
     * Trạng thái học tập của track sau khi hoàn thành bài học
     */
    trackStatus: 'completed' | 'in_progress' | 'locked';
    /**
     * XP được thưởng từ bài học này
     */
    xpAwarded: number;
    /**
     * Tổng điểm XP hiện tại của user
     */
    totalXp: number;
    /**
     * Cấp độ hiện tại của user
     */
    level: number;
    /**
     * ID của track tiếp theo vừa được mở khóa (nếu có)
     */
    unlockedTrackId: {
        [key: string]: unknown;
    } | null;
    /**
     * Thông báo kết quả
     */
    message: string;
};

export type ExerciseQuestionDto = {
    /**
     * ID câu hỏi (duy nhất trong bài tập)
     */
    id: string;
    /**
     * Nội dung câu hỏi
     */
    prompt: string;
    /**
     * Các lựa chọn (bắt buộc với QUIZ)
     */
    options?: Array<string>;
    /**
     * Đáp án đúng. KHÔNG bao giờ trả về cho học viên (bị strip khi GET).
     */
    correctAnswer: string;
    /**
     * Lời giải thích, chỉ trả cho learner sau khi chấm.
     */
    explanation: string;
};

export type CreateExerciseDto = {
    /**
     * Tiêu đề bài tập thực hành.
     */
    title: string;
    /**
     * ID của Track (UUID) chứa bài tập này.
     */
    trackId: string;
    /**
     * ID của Lesson (UUID) chứa bài tập này (nếu có).
     */
    lessonId?: string;
    /**
     * Nhãn phân loại chuyên môn.
     */
    tag: string;
    /**
     * Cấp độ khó của bài tập.
     */
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    /**
     * Thời gian ước tính hoàn thành bài tập.
     */
    estimatedTime: string;
    /**
     * Điểm kinh nghiệm nhận được sau khi hoàn thành bài tập.
     */
    xp: number;
    /**
     * Mô tả ngắn gọn về yêu cầu bài tập.
     */
    brief: string;
    /**
     * Tổng quan chi tiết về bối cảnh và hướng đi.
     */
    overview: string;
    /**
     * Danh sách tiêu chí nghiệm thu (Acceptance Criteria).
     */
    objectives: Array<string>;
    /**
     * Các bước gợi ý để thực hiện bài tập.
     */
    steps: Array<string>;
    /**
     * Danh sách ID tài liệu tham khảo (Document UUIDs).
     */
    resourceDocIds?: Array<string>;
    /**
     * Gợi ý hoặc lưu ý đặc biệt cho bài tập.
     */
    hint?: string;
    /**
     * Thể loại bài tập (GLI-92). Mặc định: PR_REVIEW.
     */
    type?: 'PR_REVIEW' | 'QUIZ' | 'FILL_IN_BLANK';
    /**
     * Cấu trúc câu hỏi + đáp án cho QUIZ/FILL_IN_BLANK (GLI-92). Chỉ Admin thấy correctAnswer.
     */
    questionsData?: Array<ExerciseQuestionDto>;
    /**
     * Điểm (%) tối thiểu để đạt khi tự động chấm (GLI-92). Mặc định: 100.
     */
    targetScore?: number;
    /**
     * Bài tập bắt buộc để hoàn thành bài học (GLI-90). Mặc định: true.
     */
    isMandatory?: boolean;
};

export type ExerciseDetailDto = {
    /**
     * ID của bài tập
     */
    id: string;
    /**
     * Tiêu đề bài tập
     */
    title: string;
    /**
     * ID của Track chứa bài tập
     */
    trackId: string;
    /**
     * Tiêu đề Track chứa bài tập
     */
    track: string;
    /**
     * Nhãn chuyên môn
     */
    tag: string;
    /**
     * Cấp độ khó
     */
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    /**
     * Thời gian ước tính hoàn thành
     */
    estimatedTime: string;
    /**
     * Số điểm XP thưởng khi hoàn thành
     */
    xp: number;
    /**
     * Tóm tắt yêu cầu bài tập
     */
    brief: string;
    /**
     * Mô tả tổng quan chi tiết bài tập
     */
    overview: string;
    objectives: Array<string>;
    steps: Array<string>;
    /**
     * Tài liệu hướng dẫn liên kết
     */
    resources: Array<DocumentResponseDto>;
    /**
     * Gợi ý giải bài tập
     */
    hint: string | null;
    /**
     * Trạng thái bài nộp cá nhân của user
     */
    status: 'pending' | 'submitted' | 'approved' | 'changes' | 'rejected';
    prUrl: string | null;
    lessonId: string | null;
    type: 'PR_REVIEW' | 'QUIZ' | 'FILL_IN_BLANK';
    questionsData: Array<ExerciseQuestionResponseDto> | null;
    targetScore: number;
    isMandatory: boolean;
};

export type AutoAnswerDto = {
    /**
     * ID câu hỏi trong questionsData
     */
    questionId: string;
    /**
     * Câu trả lời của học viên
     */
    answer: string;
};

export type SubmitAutoDto = {
    answers: Array<AutoAnswerDto>;
};

export type AutoGradeQuestionResultDto = {
    questionId: string;
    correct: boolean;
    explanation: string | null;
};

export type AutoGradeResultDto = {
    /**
     * Điểm (%) của lần làm này
     */
    score: number;
    correctCount: number;
    totalQuestions: number;
    /**
     * Điểm (%) tối thiểu để đạt
     */
    targetScore: number;
    /**
     * Lần làm này đạt hay không
     */
    passed: boolean;
    /**
     * Trạng thái hoàn thành bài tập trong DB (không đổi khi làm lại sau khi đã đạt)
     */
    completed: boolean;
    results: Array<AutoGradeQuestionResultDto>;
};

export type UpdateExerciseDto = {
    /**
     * Tiêu đề bài tập thực hành.
     */
    title?: string;
    /**
     * ID của Track (UUID) chứa bài tập này.
     */
    trackId?: string;
    /**
     * ID của Lesson (UUID) chứa bài tập này (nếu có).
     */
    lessonId?: string;
    /**
     * Nhãn phân loại chuyên môn.
     */
    tag?: string;
    /**
     * Cấp độ khó của bài tập.
     */
    difficulty?: 'Beginner' | 'Intermediate' | 'Advanced';
    /**
     * Thời gian ước tính hoàn thành bài tập.
     */
    estimatedTime?: string;
    /**
     * Điểm kinh nghiệm nhận được sau khi hoàn thành bài tập.
     */
    xp?: number;
    /**
     * Mô tả ngắn gọn về yêu cầu bài tập.
     */
    brief?: string;
    /**
     * Tổng quan chi tiết về bối cảnh và hướng đi.
     */
    overview?: string;
    /**
     * Danh sách tiêu chí nghiệm thu (Acceptance Criteria).
     */
    objectives?: Array<string>;
    /**
     * Các bước gợi ý để thực hiện bài tập.
     */
    steps?: Array<string>;
    /**
     * Danh sách ID tài liệu tham khảo (Document UUIDs).
     */
    resourceDocIds?: Array<string>;
    /**
     * Gợi ý hoặc lưu ý đặc biệt cho bài tập.
     */
    hint?: string;
    /**
     * Thể loại bài tập (GLI-92). Mặc định: PR_REVIEW.
     */
    type?: 'PR_REVIEW' | 'QUIZ' | 'FILL_IN_BLANK';
    /**
     * Cấu trúc câu hỏi + đáp án cho QUIZ/FILL_IN_BLANK (GLI-92). Chỉ Admin thấy correctAnswer.
     */
    questionsData?: Array<ExerciseQuestionDto>;
    /**
     * Điểm (%) tối thiểu để đạt khi tự động chấm (GLI-92). Mặc định: 100.
     */
    targetScore?: number;
    /**
     * Bài tập bắt buộc để hoàn thành bài học (GLI-90). Mặc định: true.
     */
    isMandatory?: boolean;
};

export type DocumentListResponseDto = {
    data: Array<DocumentResponseDto>;
    /**
     * Con trỏ trang tiếp theo
     */
    nextCursor: {
        [key: string]: unknown;
    } | null;
    /**
     * Còn dữ liệu trang kế tiếp không
     */
    hasMore: boolean;
};

export type RecentDocumentsResponseDto = {
    data: Array<DocumentResponseDto>;
};

export type CreateDocumentDto = {
    /**
     * Tiêu đề tài liệu
     */
    title: string;
    /**
     * Nội dung tài liệu hoặc mô tả ngắn
     */
    content?: string;
    /**
     * Đường dẫn liên kết bên ngoài (nếu có)
     */
    url?: string;
    /**
     * Phân loại tài liệu
     */
    kind: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
    /**
     * Danh sách các ID của thẻ phân loại (Tags) liên kết
     */
    tagIds?: Array<string>;
};

export type UpdateDocumentDto = {
    /**
     * Tiêu đề tài liệu
     */
    title?: string;
    /**
     * Nội dung tài liệu hoặc mô tả ngắn
     */
    content?: string;
    /**
     * Đường dẫn liên kết bên ngoài (nếu có)
     */
    url?: string;
    /**
     * Phân loại tài liệu
     */
    kind?: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
    /**
     * Danh sách các ID của thẻ phân loại (Tags) liên kết
     */
    tagIds?: Array<string>;
};

export type BookmarkResponseDto = {
    /**
     * ID của tài liệu kỹ thuật
     */
    documentId: string;
    /**
     * Trạng thái bookmark hiện tại của tài liệu đối với người dùng
     */
    bookmarked: boolean;
};

export type CreateTagDto = {
    /**
     * Tên thẻ phân loại
     */
    name: string;
    /**
     * Phân loại bể tag (GLI-94). Mặc định: GENERAL.
     */
    category?: 'TRACK' | 'EXERCISE' | 'DOCUMENT' | 'GENERAL';
};

export type SearchTrackResultDto = {
    /**
     * ID của Track
     */
    id: string;
    /**
     * Tên của Track
     */
    title: string;
};

export type SearchDocumentResultDto = {
    /**
     * ID của Document
     */
    id: string;
    /**
     * Tiêu đề Document
     */
    title: string;
    /**
     * Loại tài liệu
     */
    kind: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
};

export type SearchExerciseResultDto = {
    /**
     * ID của Exercise
     */
    id: string;
    /**
     * Tiêu đề bài tập
     */
    title: string;
    /**
     * Tên của Track chứa bài tập này
     */
    tag: string;
};

export type SearchResponseDto = {
    /**
     * Danh sách Tracks tìm thấy
     */
    tracks: Array<SearchTrackResultDto>;
    /**
     * Danh sách Documents tìm thấy
     */
    documents: Array<SearchDocumentResultDto>;
    /**
     * Danh sách Exercises tìm thấy
     */
    exercises: Array<SearchExerciseResultDto>;
};

export type LeaderboardEntryDto = {
    /**
     * ID của học viên.
     */
    userId: string;
    /**
     * Họ tên của học viên.
     */
    name: string;
    /**
     * Cấp độ hiện tại của học viên.
     */
    level: number;
    /**
     * Tổng điểm kinh nghiệm tích lũy.
     */
    xp: number;
    /**
     * Số ngày streak liên tục hiện tại.
     */
    streakDays: number;
    /**
     * Thứ hạng của học viên trên bảng xếp hạng.
     */
    rank: number;
};

export type LeaderboardResponseDto = {
    /**
     * Danh sách học viên trên bảng xếp hạng.
     */
    data: Array<LeaderboardEntryDto>;
    /**
     * Con trỏ base64 cho trang tiếp theo (null nếu không còn trang kế).
     */
    nextCursor: {
        [key: string]: unknown;
    } | null;
    /**
     * Có còn trang kế tiếp hay không.
     */
    hasMore: boolean;
};

export type CreateSubmissionDto = {
    /**
     * Đường dẫn GitHub PR của bài nộp
     */
    prUrl: string;
};

export type SubmissionDetailUserDto = {
    /**
     * ID của người dùng
     */
    id: string;
    /**
     * Họ tên của người dùng
     */
    name: string;
};

export type SubmissionDetailDto = {
    /**
     * ID của bài nộp
     */
    id: string;
    /**
     * ID của bài tập
     */
    exerciseId: string;
    /**
     * Tiêu đề bài tập
     */
    exercise: string;
    user: SubmissionDetailUserDto;
    /**
     * Đường dẫn Pull Request
     */
    prUrl: string;
    /**
     * Trạng thái bài nộp
     */
    status: 'pending' | 'submitted' | 'changes' | 'approved' | 'rejected';
    /**
     * ID của người chấm bài
     */
    reviewerId: {
        [key: string]: unknown;
    } | null;
    /**
     * Nhận xét của người chấm bài
     */
    reviewNote: {
        [key: string]: unknown;
    } | null;
    /**
     * Thời gian nộp bài
     */
    submittedAt: string;
    /**
     * Thời gian chấm bài
     */
    reviewedAt: {
        [key: string]: unknown;
    } | null;
};

export type SubmissionUserDto = {
    /**
     * ID của người dùng
     */
    id: string;
    /**
     * Họ tên của người dùng
     */
    name: string;
    /**
     * Màu đại diện avatar
     */
    avatarHue?: number;
};

export type SubmissionFeedItemDto = {
    /**
     * ID của bài nộp
     */
    id: string;
    user: SubmissionUserDto;
    exercise: ExerciseDetailDto;
    /**
     * Đường dẫn Pull Request
     */
    prUrl: string;
    /**
     * Trạng thái bài nộp
     */
    status: 'pending' | 'submitted' | 'changes' | 'approved' | 'rejected';
    /**
     * Thời gian nộp bài
     */
    submittedAt: string;
};

export type SubmissionListResponseDto = {
    data: Array<SubmissionFeedItemDto>;
    /**
     * Con trỏ trang tiếp theo
     */
    nextCursor: {
        [key: string]: unknown;
    } | null;
    /**
     * Còn dữ liệu trang kế tiếp không
     */
    hasMore: boolean;
};

export type ReviewSubmissionDto = {
    /**
     * Trạng thái đánh giá bài nộp
     */
    status: 'approved' | 'rejected' | 'changes';
    /**
     * Nhận xét/góp ý của người chấm
     */
    comment?: string;
};

export type SubmissionHistoryItemDto = {
    /**
     * ID của bản ghi lịch sử
     */
    id: string;
    /**
     * Đường dẫn Pull Request tại thời điểm nộp
     */
    prUrl: string;
    /**
     * Trạng thái bài nộp sau hoạt động
     */
    status: 'pending' | 'submitted' | 'changes' | 'approved' | 'rejected';
    /**
     * Thời gian thực hiện hoạt động
     */
    submittedAt: string;
    /**
     * ID của admin thực hiện hoạt động
     */
    reviewerId: {
        [key: string]: unknown;
    } | null;
    /**
     * Ghi chú đánh giá của admin
     */
    reviewNote: {
        [key: string]: unknown;
    } | null;
    /**
     * Thời gian đánh giá
     */
    reviewedAt: {
        [key: string]: unknown;
    } | null;
};

export type SubmissionHistoryResponseDto = {
    /**
     * ID của bài nộp chính
     */
    submissionId: string;
    /**
     * ID của bài tập
     */
    exerciseId: string;
    history: Array<SubmissionHistoryItemDto>;
};

export type NotificationItemDto = {
    /**
     * ID của thông báo
     */
    id: string;
    /**
     * Loại thông báo (ví dụ: submission, general)
     */
    type: string;
    /**
     * Tiêu đề thông báo
     */
    title: string;
    /**
     * Nội dung thông báo
     */
    body: string;
    /**
     * Trạng thái đã đọc hay chưa
     */
    read: boolean;
    /**
     * Thời gian tạo thông báo
     */
    createdAt: string;
};

export type NotificationListResponseDto = {
    /**
     * Danh sách thông báo
     */
    data: Array<NotificationItemDto>;
    /**
     * Số lượng thông báo chưa đọc
     */
    unreadCount: number;
};

export type MarkReadResponseDto = {
    /**
     * ID của thông báo
     */
    id: string;
    /**
     * Trạng thái đã đọc
     */
    read: boolean;
};

export type NotificationSettingsDto = {
    EXERCISE_REVIEWED: boolean;
    EXERCISE_CHANGES_REQUESTED: boolean;
    COHORT_ASSIGNED: boolean;
    NEW_LESSON_PUBLISHED: boolean;
};

export type UpdateNotificationSettingsDto = {
    EXERCISE_REVIEWED?: boolean;
    EXERCISE_CHANGES_REQUESTED?: boolean;
    COHORT_ASSIGNED?: boolean;
    NEW_LESSON_PUBLISHED?: boolean;
};

export type ExerciseQuestionResponseDto = {
    id: string;
    prompt: string;
    options?: Array<string>;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type UsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc theo Cohort ID (UUID).
         */
        cohortId?: string;
        /**
         * Lọc theo vai trò (learner / admin).
         */
        role?: string;
        /**
         * Tìm kiếm theo tên hoặc email.
         */
        q?: string;
        /**
         * Số trang.
         */
        page?: number;
        /**
         * Số lượng phần tử mỗi trang.
         */
        limit?: number;
    };
    url: '/users';
};

export type UsersControllerFindAllErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
};

export type UsersControllerFindAllResponses = {
    /**
     * Lấy danh sách thành công.
     */
    200: unknown;
};

export type UsersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerFindOneErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy người dùng.
     */
    404: unknown;
};

export type UsersControllerFindOneResponses = {
    /**
     * Lấy chi tiết thành công.
     */
    200: unknown;
};

export type UsersControllerUpdateProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersControllerUpdateProfileResponses = {
    /**
     * Cập nhật thành công.
     */
    200: unknown;
};

export type UsersControllerGetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/stats';
};

export type UsersControllerGetStatsResponses = {
    /**
     * Lấy chỉ số thành công.
     */
    200: UserDashboardStatsDto;
};

export type UsersControllerGetStatsResponse = UsersControllerGetStatsResponses[keyof UsersControllerGetStatsResponses];

export type UsersControllerClaimDailyXpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/claim-xp';
};

export type UsersControllerClaimDailyXpErrors = {
    /**
     * Bạn đã nhận XP ngày hôm nay rồi.
     */
    400: unknown;
};

export type UsersControllerClaimDailyXpResponses = {
    /**
     * Điểm danh nhận XP thành công.
     */
    200: unknown;
};

export type AdminUsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Tìm kiếm theo tên hoặc email.
         */
        q?: string;
        /**
         * Lọc theo vai trò.
         */
        role?: 'learner' | 'admin';
        /**
         * Lọc theo trạng thái hoạt động.
         */
        isActive?: string;
        /**
         * Số trang.
         */
        page?: number;
        /**
         * Số lượng phần tử mỗi trang.
         */
        limit?: number;
    };
    url: '/admin/users';
};

export type AdminUsersControllerFindAllErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
};

export type AdminUsersControllerFindAllResponses = {
    /**
     * Lấy danh sách thành công.
     */
    200: unknown;
};

export type AdminUsersControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type AdminUsersControllerCreateErrors = {
    /**
     * Dữ liệu đầu vào không hợp lệ.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Email đã tồn tại.
     */
    409: unknown;
};

export type AdminUsersControllerCreateResponses = {
    /**
     * Tạo tài khoản thành công.
     */
    201: unknown;
};

export type AdminUsersControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersControllerDeleteErrors = {
    /**
     * Không thể tự xóa tài khoản của chính mình.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy người dùng.
     */
    404: unknown;
};

export type AdminUsersControllerDeleteResponses = {
    /**
     * Xóa tài khoản thành công.
     */
    204: void;
};

export type AdminUsersControllerDeleteResponse = AdminUsersControllerDeleteResponses[keyof AdminUsersControllerDeleteResponses];

export type AdminUsersControllerUpdateData = {
    body: UpdateUserAdminDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersControllerUpdateErrors = {
    /**
     * Yêu cầu không hợp lệ hoặc tự sửa vai trò của chính mình.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy người dùng.
     */
    404: unknown;
};

export type AdminUsersControllerUpdateResponses = {
    /**
     * Cập nhật thành công.
     */
    200: unknown;
};

export type AdminUsersControllerChangeRoleData = {
    body: UpdateUserRoleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/role';
};

export type AdminUsersControllerChangeRoleErrors = {
    /**
     * Không thể tự đổi vai trò của chính mình.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy người dùng.
     */
    404: unknown;
};

export type AdminUsersControllerChangeRoleResponses = {
    /**
     * Thay đổi vai trò thành công.
     */
    200: unknown;
};

export type AdminUsersControllerChangeStatusData = {
    body: UpdateUserStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/status';
};

export type AdminUsersControllerChangeStatusErrors = {
    /**
     * Không thể tự khóa tài khoản của chính mình.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy người dùng.
     */
    404: unknown;
};

export type AdminUsersControllerChangeStatusResponses = {
    /**
     * Cập nhật trạng thái thành công.
     */
    200: unknown;
};

export type AdminUsersControllerBanUserData = {
    body: BanUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/ban';
};

export type AdminUsersControllerBanUserErrors = {
    /**
     * Không thể tự khóa tài khoản của chính mình.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy người dùng.
     */
    404: unknown;
};

export type AdminUsersControllerBanUserResponses = {
    /**
     * Khóa tài khoản thành công.
     */
    200: unknown;
};

export type AdminUsersControllerUnbanUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/unban';
};

export type AdminUsersControllerUnbanUserErrors = {
    /**
     * Không thể tự mở khóa chính mình.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy người dùng.
     */
    404: unknown;
};

export type AdminUsersControllerUnbanUserResponses = {
    /**
     * Mở khóa tài khoản thành công.
     */
    200: unknown;
};

export type AdminUsersControllerAssignCohortData = {
    body: AssignCohortDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/cohort';
};

export type AdminUsersControllerAssignCohortErrors = {
    /**
     * Yêu cầu không hợp lệ.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy người dùng hoặc cohort.
     */
    404: unknown;
    /**
     * Người dùng đã ở trong cohort này.
     */
    409: unknown;
};

export type AdminUsersControllerAssignCohortResponses = {
    /**
     * Gán cohort thành công.
     */
    200: unknown;
};

export type AuthControllerGoogleLoginData = {
    body: GoogleLoginDto;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGoogleLoginErrors = {
    /**
     * ID Token không hợp lệ.
     */
    401: unknown;
    /**
     * Email ngoài domain công ty.
     */
    403: unknown;
};

export type AuthControllerGoogleLoginResponses = {
    200: AuthResponseDto;
};

export type AuthControllerGoogleLoginResponse = AuthControllerGoogleLoginResponses[keyof AuthControllerGoogleLoginResponses];

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Dữ liệu không hợp lệ hoặc email đã tồn tại.
     */
    400: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * Tạo tài khoản thành công.
     */
    201: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Sai email hoặc mật khẩu.
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    200: AuthTokensDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRefreshData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * Refresh token không hợp lệ hoặc đã hết hạn.
     */
    401: unknown;
};

export type AuthControllerRefreshResponses = {
    200: AuthTokensDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutErrors = {
    /**
     * Thiếu hoặc sai access token.
     */
    401: unknown;
};

export type AuthControllerLogoutResponses = {
    /**
     * Logged out successfully.
     */
    200: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeErrors = {
    /**
     * Thiếu hoặc sai access token.
     */
    401: unknown;
};

export type AuthControllerMeResponses = {
    /**
     * Thông tin user (không kèm password).
     */
    200: UserProfileDto;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
    /**
     * Yêu cầu khôi phục mật khẩu thành công.
     */
    200: ForgotPasswordResponseDto;
};

export type AuthControllerForgotPasswordResponse = AuthControllerForgotPasswordResponses[keyof AuthControllerForgotPasswordResponses];

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthControllerResetPasswordErrors = {
    /**
     * Token không hợp lệ hoặc hết hạn.
     */
    400: unknown;
};

export type AuthControllerResetPasswordResponses = {
    /**
     * Mật khẩu đã được thay đổi thành công.
     */
    200: unknown;
};

export type AuthControllerChangePasswordData = {
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type AuthControllerChangePasswordErrors = {
    /**
     * Mật khẩu cũ không chính xác hoặc dữ liệu không hợp lệ.
     */
    400: unknown;
    /**
     * Thiếu hoặc sai access token.
     */
    401: unknown;
};

export type AuthControllerChangePasswordResponses = {
    /**
     * Mật khẩu đã được thay đổi thành công.
     */
    200: unknown;
};

export type CohortControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/cohorts';
};

export type CohortControllerFindAllErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
};

export type CohortControllerFindAllResponses = {
    /**
     * Lấy danh sách thành công.
     */
    200: CohortListResponseDto;
};

export type CohortControllerFindAllResponse = CohortControllerFindAllResponses[keyof CohortControllerFindAllResponses];

export type CohortControllerCreateData = {
    body: CreateCohortDto;
    path?: never;
    query?: never;
    url: '/cohorts';
};

export type CohortControllerCreateErrors = {
    /**
     * Dữ liệu đầu vào không hợp lệ.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
};

export type CohortControllerCreateResponses = {
    /**
     * Khởi tạo thành công.
     */
    201: CohortDetailDto;
};

export type CohortControllerCreateResponse = CohortControllerCreateResponses[keyof CohortControllerCreateResponses];

export type CohortControllerGetOverviewData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}/overview';
};

export type CohortControllerGetOverviewErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy Cohort.
     */
    404: unknown;
};

export type CohortControllerGetOverviewResponses = {
    /**
     * Lấy thông tin thành công.
     */
    200: CohortDashboardStatsDto;
};

export type CohortControllerGetOverviewResponse = CohortControllerGetOverviewResponses[keyof CohortControllerGetOverviewResponses];

export type CohortControllerGetUsersProgressData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        page?: number;
        limit?: number;
        /**
         * Tìm kiếm theo tên hoặc email học viên
         */
        search?: string;
        /**
         * Lọc theo một track cụ thể
         */
        trackId?: string;
    };
    url: '/cohorts/{id}/users-progress';
};

export type CohortControllerGetUsersProgressErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy Cohort.
     */
    404: unknown;
};

export type CohortControllerGetUsersProgressResponses = {
    /**
     * Lấy tiến độ thành công.
     */
    200: CohortUsersProgressResponseDto;
};

export type CohortControllerGetUsersProgressResponse = CohortControllerGetUsersProgressResponses[keyof CohortControllerGetUsersProgressResponses];

export type CohortControllerGetTrackCompletionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}/track-completion';
};

export type CohortControllerGetTrackCompletionErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy Cohort.
     */
    404: unknown;
};

export type CohortControllerGetTrackCompletionResponses = {
    /**
     * Lấy thông tin thành công.
     */
    200: CohortTrackCompletionResponseDto;
};

export type CohortControllerGetTrackCompletionResponse = CohortControllerGetTrackCompletionResponses[keyof CohortControllerGetTrackCompletionResponses];

export type CohortControllerExportReportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}/export';
};

export type CohortControllerExportReportErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy Cohort.
     */
    404: unknown;
};

export type CohortControllerExportReportResponses = {
    /**
     * Xuất báo cáo thành công.
     */
    200: unknown;
};

export type CohortControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}';
};

export type CohortControllerRemoveErrors = {
    /**
     * Không thể xóa do ràng buộc dữ liệu.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy Cohort.
     */
    404: unknown;
};

export type CohortControllerRemoveResponses = {
    /**
     * Xóa thành công.
     */
    200: unknown;
};

export type CohortControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}';
};

export type CohortControllerFindOneErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy Cohort.
     */
    404: unknown;
};

export type CohortControllerFindOneResponses = {
    /**
     * Lấy thông tin thành công.
     */
    200: CohortDetailDto;
};

export type CohortControllerFindOneResponse = CohortControllerFindOneResponses[keyof CohortControllerFindOneResponses];

export type CohortControllerUpdateData = {
    body: UpdateCohortDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/cohorts/{id}';
};

export type CohortControllerUpdateErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy Cohort.
     */
    404: unknown;
};

export type CohortControllerUpdateResponses = {
    /**
     * Cập nhật thành công.
     */
    200: CohortDetailDto;
};

export type CohortControllerUpdateResponse = CohortControllerUpdateResponses[keyof CohortControllerUpdateResponses];

export type TracksControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Số trang (mặc định: 1)
         */
        page?: number;
        /**
         * Số bản ghi trên mỗi trang (mặc định: 20, tối đa: 50)
         */
        limit?: number;
        /**
         * Lọc danh sách tracks theo trạng thái
         */
        status?: 'completed' | 'in_progress' | 'locked';
    };
    url: '/tracks';
};

export type TracksControllerFindAllResponses = {
    /**
     * Lấy danh sách tracks thành công.
     */
    200: TrackListResponseDto;
};

export type TracksControllerFindAllResponse = TracksControllerFindAllResponses[keyof TracksControllerFindAllResponses];

export type TracksControllerCreateData = {
    body: CreateTrackDto;
    path?: never;
    query?: never;
    url: '/tracks';
};

export type TracksControllerCreateResponses = {
    /**
     * Tạo track thành công.
     */
    201: unknown;
};

export type TracksControllerReorderData = {
    body: ReorderTracksDto;
    path?: never;
    query?: never;
    url: '/tracks/reorder';
};

export type TracksControllerReorderResponses = {
    /**
     * Sắp xếp lại thứ tự tracks thành công.
     */
    200: unknown;
};

export type TracksControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tracks/{id}';
};

export type TracksControllerDeleteResponses = {
    /**
     * Xóa track thành công.
     */
    204: void;
};

export type TracksControllerDeleteResponse = TracksControllerDeleteResponses[keyof TracksControllerDeleteResponses];

export type TracksControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tracks/{id}';
};

export type TracksControllerFindOneResponses = {
    /**
     * Lấy chi tiết track thành công.
     */
    200: TrackDetailDto;
};

export type TracksControllerFindOneResponse = TracksControllerFindOneResponses[keyof TracksControllerFindOneResponses];

export type TracksControllerUpdateData = {
    body: UpdateTrackDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/tracks/{id}';
};

export type TracksControllerUpdateResponses = {
    /**
     * Cập nhật track thành công.
     */
    200: unknown;
};

export type TracksControllerUpdateProgressData = {
    body: UpdateTrackProgressDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/tracks/{id}/progress';
};

export type TracksControllerUpdateProgressResponses = {
    /**
     * Cập nhật tiến độ thành công.
     */
    200: unknown;
};

export type AdminTracksControllerAdminListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/tracks';
};

export type AdminTracksControllerAdminListErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
};

export type AdminTracksControllerAdminListResponses = {
    /**
     * Lấy danh sách thành công.
     */
    200: AdminTrackListResponseDto;
};

export type AdminTracksControllerAdminListResponse = AdminTracksControllerAdminListResponses[keyof AdminTracksControllerAdminListResponses];

export type LessonsControllerFindLessonsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tracks/{id}/lessons';
};

export type LessonsControllerFindLessonsResponses = {
    /**
     * Lấy danh sách bài học thành công.
     */
    200: LessonListResponseDto;
};

export type LessonsControllerFindLessonsResponse = LessonsControllerFindLessonsResponses[keyof LessonsControllerFindLessonsResponses];

export type LessonsControllerCreateLessonData = {
    body: CreateLessonDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/tracks/{id}/lessons';
};

export type LessonsControllerCreateLessonResponses = {
    /**
     * Tạo bài học thành công.
     */
    201: unknown;
};

export type LessonsControllerDeleteLessonData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/lessons/{id}';
};

export type LessonsControllerDeleteLessonResponses = {
    /**
     * Xóa bài học thành công.
     */
    204: void;
};

export type LessonsControllerDeleteLessonResponse = LessonsControllerDeleteLessonResponses[keyof LessonsControllerDeleteLessonResponses];

export type LessonsControllerFindOneLessonData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/lessons/{id}';
};

export type LessonsControllerFindOneLessonResponses = {
    /**
     * Lấy chi tiết bài học thành công.
     */
    200: LessonDetailDto;
};

export type LessonsControllerFindOneLessonResponse = LessonsControllerFindOneLessonResponses[keyof LessonsControllerFindOneLessonResponses];

export type LessonsControllerUpdateLessonData = {
    body: UpdateLessonDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/lessons/{id}';
};

export type LessonsControllerUpdateLessonResponses = {
    /**
     * Cập nhật bài học thành công.
     */
    200: unknown;
};

export type LessonsControllerFindExercisesByLessonData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/lessons/{id}/exercises';
};

export type LessonsControllerFindExercisesByLessonResponses = {
    /**
     * Lấy danh sách bài tập thành công.
     */
    200: ExerciseListResponseDto;
};

export type LessonsControllerFindExercisesByLessonResponse = LessonsControllerFindExercisesByLessonResponses[keyof LessonsControllerFindExercisesByLessonResponses];

export type LessonsControllerCompleteLessonData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/lessons/{id}/complete';
};

export type LessonsControllerCompleteLessonResponses = {
    /**
     * Hoàn thành bài học thành công.
     */
    200: CompleteLessonResponseDto;
};

export type LessonsControllerCompleteLessonResponse = LessonsControllerCompleteLessonResponses[keyof LessonsControllerCompleteLessonResponses];

export type ExercisesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc bài tập thuộc Track cụ thể.
         */
        trackId?: string;
        /**
         * Lọc bài tập thuộc Lesson cụ thể.
         */
        lessonId?: string;
        /**
         * Lọc theo nhãn chuyên môn.
         */
        tag?: string;
        /**
         * Lọc theo cấp độ khó.
         */
        difficulty?: 'Beginner' | 'Intermediate' | 'Advanced';
        /**
         * Lọc theo trạng thái bài nộp cá nhân của Learner.
         */
        status?: 'pending' | 'submitted' | 'approved' | 'changes';
        /**
         * Số lượng phần tử tối đa trả về trên mỗi trang (phục vụ cursor pagination).
         */
        limit?: number;
        /**
         * Cursor dùng để tải trang tiếp theo (phục vụ keyset pagination).
         */
        cursor?: string;
    };
    url: '/exercises';
};

export type ExercisesControllerFindAllResponses = {
    /**
     * Lấy danh sách thành công.
     */
    200: ExerciseListResponseDto;
};

export type ExercisesControllerFindAllResponse = ExercisesControllerFindAllResponses[keyof ExercisesControllerFindAllResponses];

export type ExercisesControllerCreateData = {
    body: CreateExerciseDto;
    path?: never;
    query?: never;
    url: '/exercises';
};

export type ExercisesControllerCreateErrors = {
    /**
     * Dữ liệu đầu vào không hợp lệ.
     */
    400: unknown;
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
};

export type ExercisesControllerCreateResponses = {
    /**
     * Tạo bài tập thành công.
     */
    201: unknown;
};

export type ExercisesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type ExercisesControllerRemoveErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy bài tập.
     */
    404: unknown;
};

export type ExercisesControllerRemoveResponses = {
    /**
     * Xóa thành công.
     */
    200: unknown;
};

export type ExercisesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type ExercisesControllerFindOneErrors = {
    /**
     * Không tìm thấy bài tập.
     */
    404: unknown;
};

export type ExercisesControllerFindOneResponses = {
    /**
     * Lấy thông tin thành công.
     */
    200: ExerciseDetailDto;
};

export type ExercisesControllerFindOneResponse = ExercisesControllerFindOneResponses[keyof ExercisesControllerFindOneResponses];

export type ExercisesControllerUpdateData = {
    body: UpdateExerciseDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type ExercisesControllerUpdateErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy bài tập.
     */
    404: unknown;
};

export type ExercisesControllerUpdateResponses = {
    /**
     * Cập nhật thành công.
     */
    200: unknown;
};

export type ExercisesControllerSubmitAutoData = {
    body: SubmitAutoDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}/submit-auto';
};

export type ExercisesControllerSubmitAutoErrors = {
    /**
     * Bài tập không hỗ trợ tự chấm hoặc chưa cấu hình câu hỏi.
     */
    400: unknown;
    /**
     * Không tìm thấy bài tập.
     */
    404: unknown;
};

export type ExercisesControllerSubmitAutoResponses = {
    /**
     * Chấm điểm thành công.
     */
    200: AutoGradeResultDto;
};

export type ExercisesControllerSubmitAutoResponse = ExercisesControllerSubmitAutoResponses[keyof ExercisesControllerSubmitAutoResponses];

export type DocumentsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Từ khóa tìm kiếm trong tiêu đề hoặc nội dung tài liệu
         */
        q?: string;
        /**
         * Danh sách các thẻ phân loại (tags) phân tách bằng dấu phẩy
         */
        tags?: string;
        /**
         * Phân loại tài liệu kỹ thuật
         */
        kind?: 'Guide' | 'Reference' | 'Runbook' | 'Tutorial' | 'Link';
        /**
         * Số lượng tài liệu tối đa trả về trên mỗi trang
         */
        limit?: number;
        /**
         * Con trỏ (cursor) phục vụ phân trang
         */
        cursor?: string;
    };
    url: '/documents';
};

export type DocumentsControllerFindAllResponses = {
    /**
     * Lấy danh sách tài liệu thành công.
     */
    200: DocumentListResponseDto;
};

export type DocumentsControllerFindAllResponse = DocumentsControllerFindAllResponses[keyof DocumentsControllerFindAllResponses];

export type DocumentsControllerCreateData = {
    body: CreateDocumentDto;
    path?: never;
    query?: never;
    url: '/documents';
};

export type DocumentsControllerCreateResponses = {
    /**
     * Tạo tài liệu thành công.
     */
    201: unknown;
};

export type DocumentsControllerFindRecentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents/recent';
};

export type DocumentsControllerFindRecentResponses = {
    /**
     * Lấy tài liệu gần đây thành công.
     */
    200: RecentDocumentsResponseDto;
};

export type DocumentsControllerFindRecentResponse = DocumentsControllerFindRecentResponses[keyof DocumentsControllerFindRecentResponses];

export type DocumentsControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type DocumentsControllerDeleteResponses = {
    /**
     * Xóa tài liệu thành công.
     */
    204: void;
};

export type DocumentsControllerDeleteResponse = DocumentsControllerDeleteResponses[keyof DocumentsControllerDeleteResponses];

export type DocumentsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type DocumentsControllerFindOneResponses = {
    /**
     * Lấy chi tiết tài liệu thành công.
     */
    200: DocumentResponseDto;
};

export type DocumentsControllerFindOneResponse = DocumentsControllerFindOneResponses[keyof DocumentsControllerFindOneResponses];

export type DocumentsControllerUpdateData = {
    body: UpdateDocumentDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type DocumentsControllerUpdateResponses = {
    /**
     * Cập nhật tài liệu thành công.
     */
    200: unknown;
};

export type DocumentsControllerUnbookmarkData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}/bookmark';
};

export type DocumentsControllerUnbookmarkResponses = {
    /**
     * Hủy bookmark thành công.
     */
    204: void;
};

export type DocumentsControllerUnbookmarkResponse = DocumentsControllerUnbookmarkResponses[keyof DocumentsControllerUnbookmarkResponses];

export type DocumentsControllerBookmarkData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}/bookmark';
};

export type DocumentsControllerBookmarkResponses = {
    /**
     * Bookmark tài liệu thành công.
     */
    200: BookmarkResponseDto;
};

export type DocumentsControllerBookmarkResponse = DocumentsControllerBookmarkResponses[keyof DocumentsControllerBookmarkResponses];

export type DocumentsControllerFindAllTagsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc tag theo phân loại (GLI-94)
         */
        category?: 'TRACK' | 'EXERCISE' | 'DOCUMENT' | 'GENERAL';
    };
    url: '/tags';
};

export type DocumentsControllerFindAllTagsResponses = {
    /**
     * Lấy danh sách tags thành công.
     */
    200: unknown;
};

export type DocumentsControllerCreateTagData = {
    body: CreateTagDto;
    path?: never;
    query?: never;
    url: '/tags';
};

export type DocumentsControllerCreateTagResponses = {
    /**
     * Tạo tag thành công.
     */
    201: unknown;
};

export type DocumentsControllerDeleteTagData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tags/{id}';
};

export type DocumentsControllerDeleteTagResponses = {
    /**
     * Xóa tag thành công.
     */
    204: void;
};

export type DocumentsControllerDeleteTagResponse = DocumentsControllerDeleteTagResponses[keyof DocumentsControllerDeleteTagResponses];

export type SearchControllerGlobalSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Từ khóa tìm kiếm toàn cục
         */
        q: string;
    };
    url: '/search';
};

export type SearchControllerGlobalSearchResponses = {
    /**
     * Tìm kiếm thành công.
     */
    200: SearchResponseDto;
};

export type SearchControllerGlobalSearchResponse = SearchControllerGlobalSearchResponses[keyof SearchControllerGlobalSearchResponses];

export type LeaderboardControllerGetLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc bảng xếp hạng theo khóa học (cohort) cụ thể.
         */
        cohortId?: string;
        /**
         * Phạm vi bảng xếp hạng (cohort hoặc global). Nếu chọn cohort mà không truyền cohortId, hệ thống tự động lấy cohort của học viên hiện tại.
         */
        scope?: 'cohort' | 'global';
        /**
         * Số lượng học viên hiển thị tối đa trên bảng xếp hạng (1 - 100).
         */
        limit?: number;
        /**
         * Con trỏ base64 dùng để phân trang dựa trên (level, xp, streakDays, createdAt, id).
         */
        cursor?: string;
    };
    url: '/leaderboard';
};

export type LeaderboardControllerGetLeaderboardResponses = {
    /**
     * Lấy bảng xếp hạng thành công.
     */
    200: LeaderboardResponseDto;
};

export type LeaderboardControllerGetLeaderboardResponse = LeaderboardControllerGetLeaderboardResponses[keyof LeaderboardControllerGetLeaderboardResponses];

export type SubmissionsControllerFindExercisesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tracks/{id}/exercises';
};

export type SubmissionsControllerFindExercisesResponses = {
    /**
     * Lấy bài tập thành công.
     */
    200: unknown;
};

export type SubmissionsControllerSubmitData = {
    body: CreateSubmissionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}/submissions';
};

export type SubmissionsControllerSubmitResponses = {
    /**
     * Nộp bài tập thành công.
     */
    201: SubmissionDetailDto;
};

export type SubmissionsControllerSubmitResponse = SubmissionsControllerSubmitResponses[keyof SubmissionsControllerSubmitResponses];

export type SubmissionsControllerResubmitData = {
    body: CreateSubmissionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}/submissions';
};

export type SubmissionsControllerResubmitResponses = {
    /**
     * Nộp lại bài tập thành công.
     */
    200: SubmissionDetailDto;
};

export type SubmissionsControllerResubmitResponse = SubmissionsControllerResubmitResponses[keyof SubmissionsControllerResubmitResponses];

export type SubmissionsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lọc danh sách bài nộp theo trạng thái.
         */
        status?: 'pending' | 'submitted' | 'changes' | 'approved' | 'rejected';
        /**
         * Lọc theo ID của khóa/lớp học (Cohort).
         */
        cohortId?: string;
        /**
         * Lọc theo ID của học viên.
         */
        userId?: string;
        /**
         * Lọc theo ID của bài tập thực hành.
         */
        exerciseId?: string;
        /**
         * Số lượng bài nộp trên mỗi trang.
         */
        limit?: number;
        /**
         * Con trỏ (cursor) phục vụ phân trang
         */
        cursor?: string;
    };
    url: '/submissions';
};

export type SubmissionsControllerFindAllResponses = {
    /**
     * Lấy hàng chờ thành công.
     */
    200: SubmissionListResponseDto;
};

export type SubmissionsControllerFindAllResponse = SubmissionsControllerFindAllResponses[keyof SubmissionsControllerFindAllResponses];

export type SubmissionsControllerFindMineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/submissions/mine';
};

export type SubmissionsControllerFindMineResponses = {
    /**
     * Lấy danh sách bài nộp thành công.
     */
    200: SubmissionListResponseDto;
};

export type SubmissionsControllerFindMineResponse = SubmissionsControllerFindMineResponses[keyof SubmissionsControllerFindMineResponses];

export type SubmissionsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/submissions/{id}';
};

export type SubmissionsControllerFindOneResponses = {
    /**
     * Lấy chi tiết bài nộp thành công.
     */
    200: SubmissionDetailDto;
};

export type SubmissionsControllerFindOneResponse = SubmissionsControllerFindOneResponses[keyof SubmissionsControllerFindOneResponses];

export type SubmissionsControllerReviewData = {
    body: ReviewSubmissionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/submissions/{id}/review';
};

export type SubmissionsControllerReviewResponses = {
    /**
     * Đánh giá bài nộp thành công.
     */
    200: SubmissionDetailDto;
};

export type SubmissionsControllerReviewResponse = SubmissionsControllerReviewResponses[keyof SubmissionsControllerReviewResponses];

export type SubmissionsControllerApproveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/submissions/{id}/approve';
};

export type SubmissionsControllerApproveResponses = {
    /**
     * Phê duyệt bài nộp thành công.
     */
    200: SubmissionDetailDto;
};

export type SubmissionsControllerApproveResponse = SubmissionsControllerApproveResponses[keyof SubmissionsControllerApproveResponses];

export type SubmissionsControllerRequestChangesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/submissions/{id}/request-changes';
};

export type SubmissionsControllerRequestChangesResponses = {
    /**
     * Yêu cầu sửa đổi thành công.
     */
    200: SubmissionDetailDto;
};

export type SubmissionsControllerRequestChangesResponse = SubmissionsControllerRequestChangesResponses[keyof SubmissionsControllerRequestChangesResponses];

export type SubmissionsControllerFindHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/submissions/{id}/history';
};

export type SubmissionsControllerFindHistoryResponses = {
    /**
     * Lấy lịch sử thành công.
     */
    200: SubmissionHistoryResponseDto;
};

export type SubmissionsControllerFindHistoryResponse = SubmissionsControllerFindHistoryResponses[keyof SubmissionsControllerFindHistoryResponses];

export type NotificationsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type NotificationsControllerFindAllResponses = {
    /**
     * Lấy danh sách thành công.
     */
    200: NotificationListResponseDto;
};

export type NotificationsControllerFindAllResponse = NotificationsControllerFindAllResponses[keyof NotificationsControllerFindAllResponses];

export type NotificationsControllerMarkReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type NotificationsControllerMarkReadErrors = {
    /**
     * Không có quyền truy cập.
     */
    403: unknown;
    /**
     * Không tìm thấy thông báo.
     */
    404: unknown;
};

export type NotificationsControllerMarkReadResponses = {
    /**
     * Đánh dấu thành công.
     */
    200: MarkReadResponseDto;
};

export type NotificationsControllerMarkReadResponse = NotificationsControllerMarkReadResponses[keyof NotificationsControllerMarkReadResponses];

export type UsersControllerGetNotificationSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/notification-settings';
};

export type UsersControllerGetNotificationSettingsResponses = {
    /**
     * Lấy cấu hình thông báo thành công.
     */
    200: NotificationSettingsDto;
};

export type UsersControllerGetNotificationSettingsResponse = UsersControllerGetNotificationSettingsResponses[keyof UsersControllerGetNotificationSettingsResponses];

export type UsersControllerUpdateNotificationSettingsData = {
    body: UpdateNotificationSettingsDto;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/notification-settings';
};

export type UsersControllerUpdateNotificationSettingsResponses = {
    /**
     * Cập nhật cấu hình thông báo thành công.
     */
    200: NotificationSettingsDto;
};

export type UsersControllerUpdateNotificationSettingsResponse = UsersControllerUpdateNotificationSettingsResponses[keyof UsersControllerUpdateNotificationSettingsResponses];
